import type { ProductSeed } from '../build-product'

/** HVAC air-side equipment and pumps. */

export const HVAC_SEEDS: ProductSeed[] = [
  {
    sku: 'AFX-AHU-8000',
    name: 'Aeroflux Modular Air Handling Unit, 8,000 CMH',
    category: 'hvac',
    subcategory: 'air-handling',
    brand: 'aeroflux',
    seller: 'metro-industrial',
    price: 385000,
    listPrice: 425000,
    short: 'Double-skin modular AHU with chilled water coil, G4 pre-filter and F7 fine filter sections.',
    description:
      'A double-skin modular air handling unit built on a thermally broken aluminium frame with 25 mm PUF-injected panels, so casing condensation is not an issue at low supply temperatures. Supplied as separable sections — mixing box, filter bank, coil, fan — which is what allows a unit this size to be craned into an existing plant room through a standard door opening. The coil is a six-row chilled water coil in copper tube with aluminium fins, and the fan is a direct-driven backward-curved plug fan with an integrated EC motor, so there is no belt to tension or replace.',
    specs: {
      airflow_cmh: 8000,
      cooling_capacity_tr: 22,
      power_kw: 7.5,
      phase: 'three_phase',
      voltage_v: 415,
      filter_class: 'G4 + F7',
      material: 'aluminium',
      refrigerant: 'Chilled water',
      ip_rating: 'ip54',
      weight_kg: 620,
    },
    applications: ['hvac', 'building_services'],
    industries: ['commercial_building', 'healthcare', 'hospitality'],
    tags: ['ahu', 'air handling unit', 'double skin', 'modular', 'chilled water', 'ec fan', 'plug fan'],
    availability: 'made_to_order',
    leadTimeDays: 35,
    warrantyMonths: 24,
    certifications: ['EUROVENT', 'IS 655'],
    artwork: 'ahu',
    related: ['AFX-AHU-15000', 'AFX-FLT-F7', 'DOR-MCV-050'],
    rating: [4.6, 34],
    featured: true,
  },
  {
    sku: 'AFX-AHU-15000',
    name: 'Aeroflux Modular Air Handling Unit, 15,000 CMH',
    category: 'hvac',
    subcategory: 'air-handling',
    brand: 'aeroflux',
    seller: 'metro-industrial',
    price: 642000,
    short: 'Large-format double-skin AHU with heat recovery wheel option, sized for warehouse and atrium loads.',
    description:
      'The 15,000 CMH frame in Aeroflux’s modular range, intended for large open volumes — warehouses, atria, production halls — where a single unit is more economical than several. Same double-skin construction as the 8,000 CMH unit with an eight-row coil and twin plug fans in parallel, which keeps the unit running at reduced capacity if one fan is taken out of service. An optional heat recovery wheel section recovers up to 72% of exhaust enthalpy.',
    specs: {
      airflow_cmh: 15000,
      cooling_capacity_tr: 42,
      power_kw: 15,
      phase: 'three_phase',
      voltage_v: 415,
      filter_class: 'G4 + F7',
      material: 'aluminium',
      refrigerant: 'Chilled water',
      ip_rating: 'ip54',
      weight_kg: 1180,
    },
    applications: ['hvac', 'building_services', 'industrial_general'],
    industries: ['warehouse', 'manufacturing', 'commercial_building', 'infrastructure'],
    tags: ['ahu', 'large capacity', 'warehouse', 'heat recovery', 'twin fan'],
    availability: 'made_to_order',
    leadTimeDays: 45,
    warrantyMonths: 24,
    certifications: ['EUROVENT', 'IS 655'],
    artwork: 'ahu',
    related: ['AFX-AHU-8000', 'AFX-IFAN-400'],
  },
  {
    sku: 'AFX-FCU-600',
    name: 'Aeroflux Ceiling Concealed Fan Coil Unit, 600 CFM',
    category: 'hvac',
    subcategory: 'fan-coil-units',
    brand: 'aeroflux',
    seller: 'deccan-mep',
    price: 24500,
    listPrice: 28000,
    short: 'Slim-profile concealed FCU with three-speed EC motor and washable filter, 240 mm overall height.',
    description:
      'A ceiling-concealed fan coil unit designed to fit inside a 300 mm false ceiling void, which is the practical constraint in most fit-outs. Three-row copper-aluminium coil, galvanised steel casing with internal acoustic lining, and a three-speed EC motor that draws under 90 W at medium speed. Drain pan is stainless with an insulated underside. Supplied with a washable synthetic filter accessible from below without dropping the unit.',
    specs: {
      airflow_cmh: 1020,
      cooling_capacity_tr: 1.5,
      power_kw: 0.12,
      phase: 'single_phase',
      voltage_v: 230,
      filter_class: 'G3 washable',
      material: 'galvanised_iron',
      refrigerant: 'Chilled water',
      weight_kg: 32,
    },
    applications: ['hvac', 'building_services'],
    industries: ['commercial_building', 'hospitality', 'healthcare', 'residential'],
    tags: ['fcu', 'fan coil', 'concealed', 'slim', 'ec motor', 'false ceiling'],
    availability: 'in_stock',
    warrantyMonths: 24,
    certifications: ['IS 8148'],
    artwork: 'fcu',
    related: ['AFX-FCU-1200', 'DOR-MCV-050', 'VTK-BV2S-025'],
    rating: [4.4, 156],
    featured: true,
  },
  {
    sku: 'AFX-FCU-1200',
    name: 'Aeroflux Ceiling Concealed Fan Coil Unit, 1,200 CFM',
    category: 'hvac',
    subcategory: 'fan-coil-units',
    brand: 'aeroflux',
    seller: 'deccan-mep',
    price: 38900,
    short: 'Higher-capacity concealed FCU for open-plan floors and conference spaces.',
    description:
      'The 1,200 CFM unit in the same slim concealed range, for open-plan areas where one larger unit is preferable to several small ones. Four-row coil, higher external static capability at 60 Pa, and the same EC motor control so it can be trimmed to suit the actual duct resistance at commissioning rather than being left on high speed.',
    specs: {
      airflow_cmh: 2040,
      cooling_capacity_tr: 3,
      power_kw: 0.25,
      phase: 'single_phase',
      voltage_v: 230,
      filter_class: 'G3 washable',
      material: 'galvanised_iron',
      refrigerant: 'Chilled water',
      weight_kg: 48,
    },
    applications: ['hvac', 'building_services'],
    industries: ['commercial_building', 'hospitality', 'data_centre'],
    tags: ['fcu', 'fan coil', 'concealed', 'open plan', 'high static'],
    availability: 'in_stock',
    warrantyMonths: 24,
    certifications: ['IS 8148'],
    artwork: 'fcu',
    related: ['AFX-FCU-600', 'AFX-AHU-8000'],
  },
  {
    sku: 'AFX-IFAN-400',
    name: 'Aeroflux Inline Duct Fan, 400 mm, 4,200 CMH',
    category: 'hvac',
    subcategory: 'ventilation-fans',
    brand: 'aeroflux',
    seller: 'northline',
    price: 18400,
    short: 'Galvanised inline mixed-flow fan for toilet exhaust and general ventilation duty.',
    description:
      'A mixed-flow inline fan combining the compact casing of an axial fan with pressure capability closer to a centrifugal. Galvanised steel casing, external rotor motor with sealed-for-life bearings, and a thermal overload built into the winding. Standard duty is toilet exhaust, car park ventilation and kitchen make-up air where duct runs are long enough that a plain axial fan would stall.',
    specs: {
      airflow_cmh: 4200,
      power_kw: 1.1,
      phase: 'single_phase',
      voltage_v: 230,
      material: 'galvanised_iron',
      ip_rating: 'ip55',
      weight_kg: 18,
    },
    applications: ['hvac', 'building_services', 'industrial_general'],
    industries: ['commercial_building', 'warehouse', 'hospitality'],
    tags: ['inline fan', 'duct fan', 'mixed flow', 'exhaust', 'ventilation', '400mm'],
    availability: 'in_stock',
    warrantyMonths: 18,
    certifications: ['IS 2312'],
    artwork: 'fan',
    related: ['AFX-FLT-G4', 'AFX-AHU-8000'],
  },
  {
    sku: 'AFX-FLT-G4',
    name: 'Aeroflux Pleated Pre-Filter, G4, 595 × 595 × 48 mm',
    category: 'hvac',
    subcategory: 'filters-coils',
    brand: 'aeroflux',
    seller: 'deccan-mep',
    price: 780,
    priceUnit: 'per filter',
    short: 'Disposable pleated panel filter in a cardboard frame — the standard AHU first stage.',
    description:
      'A G4-rated pleated panel filter in a moisture-resistant cardboard frame, used as the first filtration stage in air handling units and fan coil boxes. Its job is to protect the more expensive downstream fine filter from coarse dust, and it is expected to be replaced on a three to six month cycle depending on outdoor air quality. Standard 595 mm face size fits most AHU filter banks without adaptors.',
    specs: {
      filter_class: 'G4 (ISO Coarse 60%)',
      material: 'aluminium',
      weight_kg: 0.9,
    },
    applications: ['hvac', 'building_services'],
    industries: ['commercial_building', 'healthcare', 'manufacturing'],
    tags: ['filter', 'pre-filter', 'g4', 'pleated', 'consumable', '595x595'],
    availability: 'in_stock',
    moq: 10,
    unit: 'filter',
    warrantyMonths: 0,
    certifications: ['EN 779'],
    artwork: 'filter',
    related: ['AFX-FLT-F7', 'AFX-AHU-8000'],
    rating: [4.3, 289],
  },
  {
    sku: 'AFX-FLT-F7',
    name: 'Aeroflux Bag Filter, F7, 595 × 595 × 600 mm, 6 Pocket',
    category: 'hvac',
    subcategory: 'filters-coils',
    brand: 'aeroflux',
    seller: 'deccan-mep',
    price: 2450,
    priceUnit: 'per filter',
    short: 'Synthetic media bag filter for the fine filtration stage ahead of a chilled water coil.',
    description:
      'A six-pocket synthetic bag filter rated F7, fitted downstream of the pre-filter to catch the fine particulate that would otherwise foul a coil and degrade its heat transfer. The pocket construction gives roughly ten times the media area of a panel filter in the same face size, which is what keeps the pressure drop low over a service life measured in months rather than weeks.',
    specs: {
      filter_class: 'F7 (ISO ePM1 55%)',
      material: 'aluminium',
      weight_kg: 1.8,
    },
    applications: ['hvac', 'building_services', 'pharmaceutical'],
    industries: ['commercial_building', 'healthcare', 'data_centre'],
    tags: ['filter', 'bag filter', 'f7', 'fine filter', 'epm1', 'consumable'],
    availability: 'in_stock',
    moq: 6,
    unit: 'filter',
    warrantyMonths: 0,
    certifications: ['EN 779', 'ISO 16890'],
    artwork: 'filter',
    related: ['AFX-FLT-G4', 'AFX-AHU-8000'],
  },
]

export const PUMP_SEEDS: ProductSeed[] = [
  {
    sku: 'HYM-CP-ES-050',
    name: 'Hydromek End-Suction Centrifugal Pump, DN50, 30 m³/h @ 30 m',
    category: 'pumps',
    subcategory: 'centrifugal-pumps',
    brand: 'hydromek',
    seller: 'metro-industrial',
    price: 62400,
    listPrice: 71000,
    short: 'Back-pull-out end-suction pump with cast iron casing and SS316 impeller for chilled water circulation.',
    description:
      'A back-pull-out end-suction centrifugal pump, meaning the motor and rotating assembly can be withdrawn for seal replacement without disturbing the pipework or the pump casing. Cast iron volute, SS316 impeller and shaft sleeve, and a balanced mechanical seal rated for continuous duty on closed-circuit chilled water. Mounted with the motor on a common fabricated baseplate with anti-vibration pads.',
    specs: {
      flow_rate_m3h: 30,
      head_m: 30,
      power_kw: 5.5,
      phase: 'three_phase',
      voltage_v: 415,
      size_dn: 50,
      material: 'cast_iron',
      connection_type: 'flanged',
      pressure_rating_bar: 16,
      ip_rating: 'ip55',
      temperature_max_c: 110,
      weight_kg: 96,
    },
    applications: ['hvac', 'plumbing', 'building_services', 'water_treatment'],
    industries: ['commercial_building', 'data_centre', 'manufacturing'],
    tags: ['centrifugal pump', 'end suction', 'back pull out', 'chilled water', 'ss316 impeller'],
    availability: 'in_stock',
    warrantyMonths: 24,
    certifications: ['IS 1520', 'IE3'],
    artwork: 'pump',
    related: ['HYM-CP-ES-080', 'VTK-CV-050T', 'VTK-YS-050T'],
    rating: [4.6, 88],
    featured: true,
  },
  {
    sku: 'HYM-CP-ES-080',
    name: 'Hydromek End-Suction Centrifugal Pump, DN80, 90 m³/h @ 45 m',
    category: 'pumps',
    subcategory: 'centrifugal-pumps',
    brand: 'hydromek',
    seller: 'metro-industrial',
    price: 148000,
    short: 'High-head end-suction pump for primary chilled water and pressure boosting on tall buildings.',
    description:
      'The DN80 frame in Hydromek’s end-suction range, delivering 90 m³/h against 45 m of head — a duty point typical of a primary chilled water circuit or a transfer pump feeding an upper-level tank in a high-rise. Same back-pull-out construction and SS316 wetted parts as the smaller frame, with an IE3 premium efficiency motor.',
    specs: {
      flow_rate_m3h: 90,
      head_m: 45,
      power_kw: 18.5,
      phase: 'three_phase',
      voltage_v: 415,
      size_dn: 80,
      material: 'cast_iron',
      connection_type: 'flanged',
      pressure_rating_bar: 16,
      ip_rating: 'ip55',
      temperature_max_c: 110,
      weight_kg: 214,
    },
    applications: ['hvac', 'plumbing', 'fire_fighting', 'building_services'],
    industries: ['commercial_building', 'infrastructure', 'manufacturing'],
    tags: ['centrifugal pump', 'high head', 'primary circuit', 'ie3', 'dn80'],
    availability: 'made_to_order',
    leadTimeDays: 18,
    warrantyMonths: 24,
    certifications: ['IS 1520', 'IE3'],
    artwork: 'pump',
    related: ['HYM-CP-ES-050', 'HYM-BST-VS3'],
  },
  {
    sku: 'HYM-SUB-DW-15',
    name: 'Hydromek Submersible Dewatering Pump, 1.5 kW, 15 m³/h',
    category: 'pumps',
    subcategory: 'submersible-pumps',
    brand: 'hydromek',
    seller: 'westward-supply',
    price: 18600,
    listPrice: 22400,
    short: 'Portable dewatering pump with agitator and hardened impeller for silty construction water.',
    description:
      'A portable submersible pump for construction dewatering — basement excavations, lift pits, flooded plant rooms. The bottom-entry agitator keeps settled silt in suspension so it passes through rather than blocking the strainer, and the impeller is hardened cast iron to survive abrasive water. Continuous-duty rated with the motor cooled by the pumped liquid. Comes with 10 m of buoyant cable and a 50 mm hose tail.',
    specs: {
      flow_rate_m3h: 15,
      head_m: 14,
      power_kw: 1.5,
      phase: 'single_phase',
      voltage_v: 230,
      size_dn: 50,
      material: 'cast_iron',
      connection_type: 'threaded',
      ip_rating: 'ip68',
      weight_kg: 21,
    },
    applications: ['water_treatment', 'industrial_general', 'plumbing'],
    industries: ['infrastructure', 'manufacturing', 'warehouse'],
    tags: ['submersible', 'dewatering', 'construction', 'portable', 'agitator', 'silt'],
    availability: 'in_stock',
    warrantyMonths: 12,
    certifications: ['IS 8034'],
    artwork: 'pump-submersible',
    related: ['HYM-SUB-SW-30', 'HYM-CP-ES-050'],
    rating: [4.2, 174],
  },
  {
    sku: 'HYM-SUB-SW-30',
    name: 'Hydromek Submersible Sewage Pump, 3 kW, Non-Clog Vortex',
    category: 'pumps',
    subcategory: 'submersible-pumps',
    brand: 'hydromek',
    seller: 'northline',
    price: 44800,
    short: 'Vortex-impeller sewage pump passing 76 mm solids, for wet wells and sewage treatment inlets.',
    description:
      'A non-clog vortex impeller pump for raw sewage and effluent. The recessed vortex impeller creates a flow field that carries solids through the casing without contacting the impeller vanes, which is why it will pass 76 mm solids and rag without blocking — the failure mode that takes conventional pumps out of service. Double mechanical seal in an oil chamber with a moisture sensor. Suits guide-rail duckfoot installation.',
    specs: {
      flow_rate_m3h: 36,
      head_m: 18,
      power_kw: 3,
      phase: 'three_phase',
      voltage_v: 415,
      size_dn: 80,
      material: 'cast_iron',
      connection_type: 'flanged',
      ip_rating: 'ip68',
      weight_kg: 58,
    },
    applications: ['water_treatment', 'plumbing', 'industrial_general'],
    industries: ['infrastructure', 'commercial_building', 'manufacturing'],
    tags: ['sewage pump', 'submersible', 'vortex', 'non clog', 'stp', 'wet well'],
    availability: 'in_stock',
    warrantyMonths: 18,
    certifications: ['IS 14805'],
    artwork: 'pump-submersible',
    related: ['HYM-SUB-DW-15', 'HYM-DOS-25'],
  },
  {
    sku: 'HYM-BST-VS3',
    name: 'Hydromek Variable Speed Booster Set, 3 Pump, 45 m³/h',
    category: 'pumps',
    subcategory: 'booster-sets',
    brand: 'hydromek',
    seller: 'coastal-flow',
    price: 486000,
    short: 'Triplex booster set with VFD control holding constant outlet pressure across the full demand range.',
    description:
      'Three vertical multistage pumps on a common manifold under a variable frequency drive controller, holding a constant outlet pressure as demand varies from a single tap to full building draw. The controller cascades pumps in and out and rotates the duty pump on a timer so wear is shared evenly. Stainless manifold, diaphragm accumulator, dry-run protection and a pressure transducer with a local display. Standard configuration for domestic water pressurisation in buildings above eight floors.',
    specs: {
      flow_rate_m3h: 45,
      head_m: 60,
      power_kw: 16.5,
      phase: 'three_phase',
      voltage_v: 415,
      size_dn: 80,
      material: 'stainless_steel',
      connection_type: 'flanged',
      pressure_rating_bar: 16,
      ip_rating: 'ip55',
      weight_kg: 340,
    },
    applications: ['plumbing', 'building_services', 'hvac'],
    industries: ['commercial_building', 'residential', 'hospitality', 'healthcare'],
    tags: ['booster set', 'vfd', 'variable speed', 'triplex', 'pressure boosting', 'multistage'],
    availability: 'made_to_order',
    leadTimeDays: 40,
    warrantyMonths: 36,
    certifications: ['IS 1520', 'CE'],
    artwork: 'booster-set',
    related: ['HYM-CP-ES-080', 'DOR-PRV-050'],
    rating: [4.7, 26],
    featured: true,
  },
  {
    sku: 'HYM-DOS-25',
    name: 'Hydromek Electronic Dosing Pump, 25 L/h, PVDF Head',
    category: 'pumps',
    subcategory: 'dosing-pumps',
    brand: 'hydromek',
    seller: 'westward-supply',
    price: 26400,
    short: 'Solenoid metering pump with PVDF liquid end for chlorine, antiscalant and pH correction dosing.',
    description:
      'A solenoid-driven diaphragm metering pump for chemical treatment — sodium hypochlorite, antiscalant, acid and alkali dosing on water treatment plants and cooling towers. The PVDF liquid end and PTFE diaphragm resist the chemicals that destroy polypropylene heads within months. Stroke length and frequency are both adjustable, giving a 1000:1 turndown, and the pump accepts an external 4–20 mA signal for proportional dosing.',
    specs: {
      flow_rate_m3h: 0.025,
      head_m: 70,
      power_kw: 0.05,
      phase: 'single_phase',
      voltage_v: 230,
      material: 'ppr',
      connection_type: 'threaded',
      pressure_rating_bar: 7,
      ip_rating: 'ip65',
      weight_kg: 3.4,
    },
    applications: ['water_treatment', 'chemical', 'industrial_general'],
    industries: ['manufacturing', 'commercial_building', 'process_plant'],
    tags: ['dosing pump', 'metering', 'pvdf', 'chlorine', 'antiscalant', '4-20ma'],
    availability: 'in_stock',
    warrantyMonths: 18,
    certifications: ['CE'],
    artwork: 'pump-dosing',
    related: ['HYM-SUB-SW-30', 'TRU-PG-100'],
  },
  {
    sku: 'HYM-JCK-22',
    name: 'Hydromek Fire Jockey Pump, 2.2 kW, Multistage Vertical',
    category: 'pumps',
    subcategory: 'centrifugal-pumps',
    brand: 'hydromek',
    seller: 'coastal-flow',
    price: 58900,
    short: 'Pressure-maintenance pump holding the fire main charged so the main pump only starts on a real demand.',
    description:
      'A jockey pump exists to make good the small leaks that every sprinkler and hydrant main has, so that the main fire pump starts only when a sprinkler head actually operates. Vertical multistage construction in stainless steel, sized to a low flow at high head, wired to cut in and out on a narrow pressure band above the main pump start point. Mandatory on any hydrant or sprinkler installation designed to IS 15105 or NFPA 20.',
    specs: {
      flow_rate_m3h: 3.6,
      head_m: 75,
      power_kw: 2.2,
      phase: 'three_phase',
      voltage_v: 415,
      size_dn: 32,
      material: 'stainless_steel',
      connection_type: 'threaded',
      pressure_rating_bar: 16,
      ip_rating: 'ip55',
      weight_kg: 42,
    },
    applications: ['fire_fighting', 'building_services'],
    industries: ['commercial_building', 'warehouse', 'manufacturing', 'infrastructure'],
    tags: ['jockey pump', 'fire pump', 'pressure maintenance', 'multistage', 'nfpa 20', 'is 15105'],
    availability: 'in_stock',
    warrantyMonths: 24,
    certifications: ['IS 15105', 'NFPA 20'],
    artwork: 'pump',
    related: ['PYR-SPK-PEN-68', 'HYM-CP-ES-080'],
  },
]
