import type { ProductSeed } from '../build-product'

/** Plumbing, piping and general plant equipment. */

export const PLUMBING_SEEDS: ProductSeed[] = [
  {
    sku: 'CPL-CU-22',
    name: 'Copperline Copper Tube, 22 mm × 0.9 mm, Half-Hard, 3 m',
    category: 'plumbing',
    subcategory: 'pipes',
    brand: 'copperline',
    seller: 'metro-industrial',
    price: 1980,
    listPrice: 2280,
    priceUnit: 'per 3 m length',
    short: 'EN 1057 R250 half-hard copper tube for hot and cold water distribution and medical gas.',
    description:
      'Half-hard copper tube to EN 1057 R250, 22 mm outside diameter with a 0.9 mm wall, supplied in straight 3 m lengths. Half-hard temper holds its shape in a straight run and still takes a bend on a former, which is why it is the standard specification for exposed pipework. Degreased and capped for medical gas service. Joints by capillary soldering or press fitting; do not use compression fittings on concealed runs.',
    specs: {
      material: 'copper',
      outer_diameter_mm: 22,
      wall_thickness_mm: 0.9,
      length_m: 3,
      connection_type: 'brazed',
      pressure_rating_bar: 40,
      temperature_max_c: 110,
      weight_kg: 1.6,
    },
    applications: ['plumbing', 'hvac', 'building_services', 'pharmaceutical'],
    industries: ['commercial_building', 'healthcare', 'hospitality', 'residential'],
    tags: ['copper pipe', 'copper tube', '22mm', 'en 1057', 'half hard', 'medical gas', 'r250'],
    availability: 'in_stock',
    moq: 5,
    unit: 'length',
    warrantyMonths: 12,
    certifications: ['EN 1057', 'IS 191'],
    artwork: 'pipe',
    related: ['CPL-CU-54', 'CPL-INS-NBR-25', 'GRW-PW-450'],
    rating: [4.6, 224],
    featured: true,
  },
  {
    sku: 'CPL-CU-54',
    name: 'Copperline Copper Tube, 54 mm × 1.2 mm, Half-Hard, 3 m',
    category: 'plumbing',
    subcategory: 'pipes',
    brand: 'copperline',
    seller: 'metro-industrial',
    price: 6450,
    priceUnit: 'per 3 m length',
    short: 'Large-bore copper tube for main risers and plant room distribution.',
    description:
      'The 54 mm size in Copperline’s EN 1057 range, used for main risers and plant room headers where copper is specified throughout. At this diameter a capillary joint needs a proper heat source — a standard blowtorch will not bring the joint to soldering temperature evenly, and a cold joint on a riser is an expensive thing to find later.',
    specs: {
      material: 'copper',
      outer_diameter_mm: 54,
      wall_thickness_mm: 1.2,
      length_m: 3,
      connection_type: 'brazed',
      pressure_rating_bar: 25,
      temperature_max_c: 110,
      weight_kg: 5.3,
    },
    applications: ['plumbing', 'hvac', 'building_services'],
    industries: ['commercial_building', 'healthcare', 'hospitality'],
    tags: ['copper pipe', '54mm', 'riser', 'en 1057', 'large bore'],
    availability: 'in_stock',
    moq: 3,
    unit: 'length',
    warrantyMonths: 12,
    certifications: ['EN 1057', 'IS 191'],
    artwork: 'pipe',
    related: ['CPL-CU-22', 'CPL-INS-NBR-25'],
  },
  {
    sku: 'CPL-CPVC-50',
    name: 'Copperline CPVC Pipe, DN50, SDR 11, 3 m',
    category: 'plumbing',
    subcategory: 'pipes',
    brand: 'copperline',
    seller: 'deccan-mep',
    price: 1240,
    priceUnit: 'per 3 m length',
    short: 'Hot-water-rated CPVC pipe joined by solvent cement, for domestic distribution up to 93 °C.',
    description:
      'CPVC pipe to SDR 11, rated for continuous hot water service at 93 °C, which is what separates it from ordinary uPVC. Joined with solvent cement — a chemical weld, not a glue, and it needs the specified cure time before pressure testing regardless of what the site programme says. Lighter and far quicker to install than copper, and immune to the pinhole corrosion that affects copper in aggressive water.',
    specs: {
      material: 'cpvc',
      size_dn: 50,
      outer_diameter_mm: 57,
      wall_thickness_mm: 5.2,
      length_m: 3,
      connection_type: 'solvent_weld',
      pressure_rating_bar: 16,
      temperature_max_c: 93,
      weight_kg: 2.4,
    },
    applications: ['plumbing', 'building_services', 'hvac'],
    industries: ['residential', 'commercial_building', 'hospitality'],
    tags: ['cpvc', 'pipe', 'dn50', 'sdr 11', 'hot water', 'solvent weld'],
    availability: 'in_stock',
    moq: 5,
    unit: 'length',
    warrantyMonths: 24,
    certifications: ['ASTM D2846', 'IS 15778'],
    artwork: 'pipe',
    related: ['CPL-CPVC-BV-050', 'CPL-CU-22'],
    rating: [4.3, 291],
  },
  {
    sku: 'CPL-CPVC-BV-050',
    name: 'Copperline CPVC Ball Valve, DN50, Solvent Weld',
    category: 'plumbing',
    subcategory: 'fittings',
    brand: 'copperline',
    seller: 'deccan-mep',
    price: 690,
    short: 'True-union CPVC isolation valve matched to the CPVC pipe system, no metal in the wetted path.',
    description:
      'A true-union CPVC ball valve with EPDM seals, matched to the CPVC pipe system so there is no dissimilar-metal transition. The union nuts either side let the valve be removed without cutting the pipe, which is the only practical way to service a solvent-welded system. Do not use on chilled water below 5 °C — CPVC becomes brittle at low temperature.',
    specs: {
      valve_type: 'ball',
      material: 'cpvc',
      size_dn: 50,
      connection_type: 'solvent_weld',
      pressure_rating_bar: 16,
      temperature_max_c: 93,
      operation: 'manual_lever',
      seat_material: 'EPDM',
      weight_kg: 0.48,
    },
    applications: ['plumbing', 'building_services', 'water_treatment'],
    industries: ['residential', 'commercial_building'],
    tags: ['cpvc valve', 'ball valve', 'true union', 'solvent weld', 'plastic', 'dn50'],
    availability: 'in_stock',
    warrantyMonths: 18,
    certifications: ['ASTM D2846'],
    artwork: 'ball-valve',
    related: ['CPL-CPVC-50', 'VTK-BVB-050'],
  },
  {
    sku: 'CPL-GI-50',
    name: 'Copperline GI Pipe, DN50 Medium Class, Threaded, 6 m',
    category: 'plumbing',
    subcategory: 'pipes',
    brand: 'copperline',
    seller: 'westward-supply',
    price: 3980,
    priceUnit: 'per 6 m length',
    short: 'IS 1239 medium-class galvanised steel pipe with threaded ends and socket, for fire and utility mains.',
    description:
      'Medium-class galvanised iron pipe to IS 1239, supplied in 6 m lengths with threaded ends and one socket. Still the default for hydrant mains, sprinkler distribution and compressed air, where its mechanical robustness matters more than its weight. Threads should be sealed with PTFE tape and a jointing compound; a dry thread will weep on a fire main under test.',
    specs: {
      material: 'galvanised_iron',
      size_dn: 50,
      outer_diameter_mm: 60.3,
      wall_thickness_mm: 3.6,
      length_m: 6,
      connection_type: 'threaded',
      pressure_rating_bar: 25,
      temperature_max_c: 120,
      weight_kg: 30.2,
    },
    applications: ['fire_fighting', 'plumbing', 'compressed_air', 'industrial_general'],
    industries: ['commercial_building', 'warehouse', 'manufacturing', 'infrastructure'],
    tags: ['gi pipe', 'galvanised', 'is 1239', 'medium class', 'threaded', 'dn50', 'fire main'],
    availability: 'in_stock',
    moq: 3,
    unit: 'length',
    warrantyMonths: 12,
    certifications: ['IS 1239'],
    artwork: 'pipe',
    related: ['PYR-HYD-DH-63', 'CPL-CLAMP-50'],
  },
  {
    sku: 'CPL-INS-NBR-25',
    name: 'Copperline Nitrile Rubber Pipe Insulation, 25 mm Wall, 54 mm Bore',
    category: 'plumbing',
    subcategory: 'insulation',
    brand: 'copperline',
    seller: 'metro-industrial',
    price: 480,
    priceUnit: 'per 2 m length',
    short: 'Closed-cell elastomeric insulation with a high vapour resistance — the correct choice for chilled water.',
    description:
      'Closed-cell nitrile rubber insulation, 25 mm wall for a 54 mm bore. On chilled water the insulation is not primarily there to save energy — it is there to stop condensation forming on the pipe surface, and that requires a closed cell structure with a high water vapour diffusion resistance. Glass wool will not do it. Every joint must be glued, not taped, or moisture tracks along the pipe under the insulation and corrodes it invisibly.',
    specs: {
      material: 'ppr',
      outer_diameter_mm: 104,
      wall_thickness_mm: 25,
      length_m: 2,
      temperature_max_c: 105,
      weight_kg: 0.7,
    },
    applications: ['hvac', 'plumbing', 'building_services'],
    industries: ['commercial_building', 'data_centre', 'healthcare'],
    tags: ['insulation', 'nitrile', 'elastomeric', 'closed cell', 'chilled water', 'condensation', '25mm'],
    availability: 'in_stock',
    moq: 10,
    unit: 'length',
    warrantyMonths: 12,
    certifications: ['ASTM C534', 'BS 476 Part 7'],
    artwork: 'insulation',
    related: ['CPL-CU-54', 'CPL-CLAMP-50'],
    rating: [4.5, 163],
  },
  {
    sku: 'CPL-CLAMP-50',
    name: 'Copperline Pipe Clamp with Rubber Lining, DN50, M10 Boss',
    category: 'plumbing',
    subcategory: 'supports',
    brand: 'copperline',
    seller: 'westward-supply',
    price: 145,
    priceUnit: 'per clamp',
    short: 'Two-part galvanised clamp with EPDM lining that isolates pipe vibration from the structure.',
    description:
      'A two-part galvanised steel pipe clamp with a bonded EPDM lining and an M10 threaded boss. The rubber lining does two jobs: it breaks the vibration path from pipe to structure, and it allows the pipe to expand and contract longitudinally without scoring. A metal-to-metal clamp on a hot water line will transmit every pump harmonic into the slab above.',
    specs: {
      material: 'galvanised_iron',
      size_dn: 50,
      outer_diameter_mm: 60,
      temperature_max_c: 110,
      weight_kg: 0.24,
    },
    applications: ['plumbing', 'hvac', 'fire_fighting', 'building_services'],
    industries: ['commercial_building', 'warehouse', 'manufacturing'],
    tags: ['pipe clamp', 'support', 'rubber lined', 'epdm', 'm10', 'anti vibration'],
    availability: 'in_stock',
    moq: 25,
    unit: 'clamp',
    warrantyMonths: 12,
    certifications: ['IS 2629'],
    artwork: 'clamp',
    related: ['CPL-GI-50', 'CPL-INS-NBR-25'],
  },
]

export const INDUSTRIAL_SEEDS: ProductSeed[] = [
  {
    sku: 'SGD-COMP-SCR-15',
    name: 'Steelgrid Rotary Screw Air Compressor, 15 kW, 8 bar, 2.4 m³/min',
    category: 'industrial',
    subcategory: 'compressors',
    brand: 'steelgrid',
    seller: 'northline',
    price: 428000,
    listPrice: 475000,
    short: 'Belt-driven screw compressor with integrated dryer and receiver, for continuous plant air duty.',
    description:
      'A 15 kW oil-injected rotary screw compressor delivering 2.4 m³/min at 8 bar, supplied as a package with a 500 litre receiver and an integrated refrigerated dryer. Screw compressors are the correct choice above roughly 50% duty cycle — a reciprocating machine at continuous duty overheats and its rings fail. Sound-attenuated canopy rated 68 dB(A) at one metre, which is quiet enough to sit in a plant room without hearing protection.',
    specs: {
      power_kw: 15,
      phase: 'three_phase',
      voltage_v: 415,
      pressure_rating_bar: 8,
      material: 'carbon_steel',
      ip_rating: 'ip54',
      connection_type: 'threaded',
      size_dn: 25,
      weight_kg: 420,
    },
    applications: ['compressed_air', 'industrial_general'],
    industries: ['manufacturing', 'warehouse', 'process_plant'],
    tags: ['air compressor', 'screw compressor', '15kw', '8 bar', 'refrigerated dryer', 'receiver'],
    availability: 'made_to_order',
    leadTimeDays: 25,
    warrantyMonths: 24,
    certifications: ['CE', 'IS 5456'],
    artwork: 'compressor',
    related: ['SGD-MOT-IE3-75', 'TRU-PG-100', 'CPL-GI-50'],
    rating: [4.5, 41],
    featured: true,
  },
  {
    sku: 'SGD-MOT-IE3-75',
    name: 'Steelgrid Induction Motor, 7.5 kW, 4 Pole, IE3, B3 Foot Mount',
    category: 'industrial',
    subcategory: 'motors-drives',
    brand: 'steelgrid',
    seller: 'westward-supply',
    price: 34200,
    short: 'Premium-efficiency TEFC squirrel cage motor in a cast iron frame, 1,440 rpm at 415 V.',
    description:
      'A 7.5 kW four-pole totally-enclosed fan-cooled induction motor in a cast iron frame, IE3 premium efficiency as required by the current energy conservation rules for new installations. Class F insulation with Class B temperature rise, giving thermal headroom for the voltage variation typical of an Indian industrial supply. Foot mounted B3, frame size 132M, suitable for direct-on-line or inverter operation.',
    specs: {
      power_kw: 7.5,
      phase: 'three_phase',
      voltage_v: 415,
      current_rating_a: 15,
      material: 'cast_iron',
      ip_rating: 'ip55',
      weight_kg: 62,
    },
    applications: ['industrial_general', 'building_services'],
    industries: ['manufacturing', 'process_plant', 'warehouse'],
    tags: ['motor', 'induction motor', 'ie3', '7.5kw', '4 pole', 'tefc', 'b3', 'frame 132m'],
    availability: 'in_stock',
    warrantyMonths: 24,
    certifications: ['IS 12615', 'IE3'],
    artwork: 'motor',
    related: ['SGD-VFD-75', 'SNC-CONT-25', 'HYM-CP-ES-050'],
    rating: [4.6, 87],
  },
  {
    sku: 'SGD-VFD-75',
    name: 'Steelgrid Variable Frequency Drive, 7.5 kW, 3 Phase, IP20',
    category: 'industrial',
    subcategory: 'motors-drives',
    brand: 'steelgrid',
    seller: 'deccan-mep',
    price: 28900,
    short: 'Sensorless vector drive with built-in PID for pump and fan speed control.',
    description:
      'A 7.5 kW sensorless vector VFD with an on-board PID controller, which is what allows a pump or fan to hold a pressure or temperature set point without an external controller. Includes a built-in EMC filter, DC bus choke and a keypad with copy function for commissioning several identical drives. Running a centrifugal load at 80% speed draws roughly half the power, which is where the payback comes from — not from the drive itself.',
    specs: {
      power_kw: 7.5,
      phase: 'three_phase',
      voltage_v: 415,
      current_rating_a: 17,
      material: 'carbon_steel',
      ip_rating: 'ip20',
      weight_kg: 4.8,
    },
    applications: ['industrial_general', 'hvac', 'building_services', 'water_treatment'],
    industries: ['manufacturing', 'commercial_building', 'data_centre'],
    tags: ['vfd', 'variable frequency drive', 'inverter', '7.5kw', 'sensorless vector', 'pid', 'emc filter'],
    availability: 'in_stock',
    warrantyMonths: 24,
    certifications: ['CE', 'IEC 61800-5-1'],
    artwork: 'vfd',
    related: ['SGD-MOT-IE3-75', 'HYM-BST-VS3', 'AFX-IFAN-400'],
    rating: [4.7, 58],
    featured: true,
  },
  {
    sku: 'SGD-HOIST-2T',
    name: 'Steelgrid Chain Hoist, 2 Tonne, 3 m Lift, Manual',
    category: 'industrial',
    subcategory: 'material-handling',
    brand: 'steelgrid',
    seller: 'northline',
    price: 12400,
    short: 'Hand chain block with Grade 80 load chain and mechanical load brake, tested to 1.5× rated load.',
    description:
      'A 2 tonne hand chain block with a 3 metre lift, Grade 80 alloy load chain and a Weston-type mechanical load brake that holds the load automatically at any point in the lift. Every unit is proof tested to 1.5 times its rated load with a certificate supplied. Inspect the chain for stretch and the hook throat for opening before each use — a hoist that has been overloaded shows it in the hook geometry before it shows it in the chain.',
    specs: {
      material: 'carbon_steel',
      weight_kg: 18.5,
    },
    applications: ['industrial_general', 'building_services'],
    industries: ['manufacturing', 'warehouse', 'infrastructure'],
    tags: ['chain hoist', 'chain block', '2 tonne', 'grade 80', 'load brake', 'lifting', 'proof tested'],
    availability: 'in_stock',
    warrantyMonths: 12,
    certifications: ['IS 3832', 'EN 13157'],
    artwork: 'hoist',
    related: ['SGD-MOT-IE3-75', 'NRV-HRN-2PT'],
  },
]
