import type { ProductSeed } from '../build-product'

/** Electrical protection, fire fighting, instrumentation, tools and PPE. */

export const ELECTRICAL_SEEDS: ProductSeed[] = [
  {
    sku: 'SNC-MCCB-100-3P',
    name: 'Sanchay MCCB, 100 A, 3 Pole, 25 kA Thermal-Magnetic',
    category: 'electrical',
    subcategory: 'circuit-breakers',
    brand: 'sanchay',
    seller: 'northline',
    price: 8450,
    listPrice: 9900,
    short: 'Three-pole moulded case circuit breaker with adjustable thermal trip, 25 kA breaking capacity.',
    description:
      'A thermal-magnetic moulded case circuit breaker for incomer and outgoing feeder protection in low-voltage distribution boards. The thermal element is adjustable from 70% to 100% of rated current, which lets one frame size cover several cable sizes rather than stocking a breaker per circuit. Fixed magnetic trip at ten times rated current handles short circuits. Rated 25 kA at 415 V — adequate for most commercial buildings; verify against the transformer fault level before specifying.',
    specs: {
      current_rating_a: 100,
      breaking_capacity_ka: 25,
      poles: 3,
      voltage_v: 415,
      ip_rating: 'ip20',
      material: 'carbon_steel',
      weight_kg: 1.6,
    },
    applications: ['building_services', 'industrial_general', 'power'],
    industries: ['commercial_building', 'manufacturing', 'warehouse', 'data_centre'],
    tags: ['mccb', 'circuit breaker', '100a', '3 pole', '25ka', 'thermal magnetic', 'distribution'],
    availability: 'in_stock',
    warrantyMonths: 24,
    certifications: ['IS/IEC 60947-2'],
    artwork: 'breaker',
    related: ['SNC-MCCB-250-4P', 'SNC-MCB-32-C', 'SNC-DB-12W'],
    rating: [4.5, 203],
    featured: true,
  },
  {
    sku: 'SNC-MCCB-250-4P',
    name: 'Sanchay MCCB, 250 A, 4 Pole, 36 kA Microprocessor Release',
    category: 'electrical',
    subcategory: 'circuit-breakers',
    brand: 'sanchay',
    seller: 'northline',
    price: 27600,
    short: 'Four-pole MCCB with electronic trip unit providing adjustable long, short and instantaneous protection.',
    description:
      'A four-pole MCCB with a microprocessor-based trip unit rather than a bimetal strip. Long-time, short-time and instantaneous protection are each independently adjustable, which is what makes proper discrimination possible — an upstream breaker can be set to hold while the downstream device clears the fault, so a single circuit failure does not take out the whole board. Includes neutral protection at 50% or 100% and an LED trip cause indicator.',
    specs: {
      current_rating_a: 250,
      breaking_capacity_ka: 36,
      poles: 4,
      voltage_v: 415,
      ip_rating: 'ip20',
      material: 'carbon_steel',
      weight_kg: 4.2,
    },
    applications: ['building_services', 'industrial_general', 'power'],
    industries: ['data_centre', 'manufacturing', 'infrastructure', 'commercial_building'],
    tags: ['mccb', '250a', '4 pole', '36ka', 'electronic trip', 'discrimination', 'lsi'],
    availability: 'in_stock',
    warrantyMonths: 36,
    certifications: ['IS/IEC 60947-2'],
    artwork: 'breaker',
    related: ['SNC-MCCB-100-3P', 'SNC-DB-12W'],
    rating: [4.7, 71],
  },
  {
    sku: 'SNC-MCB-32-C',
    name: 'Sanchay MCB, 32 A, Single Pole, C-Curve, 10 kA',
    category: 'electrical',
    subcategory: 'circuit-breakers',
    brand: 'sanchay',
    seller: 'deccan-mep',
    price: 285,
    listPrice: 340,
    short: 'DIN-rail miniature circuit breaker with C-curve characteristic for mixed lighting and socket circuits.',
    description:
      'A single-pole 32 A miniature circuit breaker on a 35 mm DIN rail mount. The C-curve trips between five and ten times rated current on magnetic action, which tolerates the inrush of fluorescent ballasts and small motors without nuisance tripping while still clearing a genuine fault quickly. B-curve is the correct choice for pure resistive lighting; D-curve for high-inrush machinery.',
    specs: {
      current_rating_a: 32,
      breaking_capacity_ka: 10,
      poles: 1,
      voltage_v: 240,
      ip_rating: 'ip20',
      material: 'carbon_steel',
      weight_kg: 0.11,
    },
    applications: ['building_services', 'industrial_general'],
    industries: ['commercial_building', 'residential', 'hospitality', 'warehouse'],
    tags: ['mcb', '32a', 'c curve', 'din rail', '10ka', 'single pole', 'lighting circuit'],
    availability: 'in_stock',
    moq: 12,
    warrantyMonths: 24,
    certifications: ['IS/IEC 60898-1'],
    artwork: 'breaker-mcb',
    related: ['SNC-MCCB-100-3P', 'SNC-DB-12W', 'SNC-CONT-25'],
    rating: [4.4, 512],
  },
  {
    sku: 'SNC-CONT-25',
    name: 'Sanchay Contactor, 25 A, 3 Pole, 230 V AC Coil',
    category: 'electrical',
    subcategory: 'switchgear',
    brand: 'sanchay',
    seller: 'deccan-mep',
    price: 1240,
    short: 'AC-3 rated three-pole contactor for motor switching up to 11 kW at 415 V.',
    description:
      'A three-pole contactor rated AC-3 for direct-on-line motor starting up to 11 kW. Silver alloy contacts, a 230 V AC coil, and one normally-open auxiliary contact built in. Designed to accept a front-mounted thermal overload relay to form a complete starter. AC-3 rating is the one that matters for motor duty — AC-1 figures describe resistive loads and will overstate the contactor by a factor of two or more.',
    specs: {
      current_rating_a: 25,
      poles: 3,
      voltage_v: 415,
      breaking_capacity_ka: 6,
      ip_rating: 'ip20',
      material: 'carbon_steel',
      weight_kg: 0.42,
    },
    applications: ['building_services', 'industrial_general', 'hvac'],
    industries: ['manufacturing', 'commercial_building', 'warehouse'],
    tags: ['contactor', '25a', '3 pole', 'ac-3', 'motor starter', 'dol'],
    availability: 'in_stock',
    warrantyMonths: 18,
    certifications: ['IS/IEC 60947-4-1'],
    artwork: 'contactor',
    related: ['SNC-MCB-32-C', 'HYM-CP-ES-050'],
  },
  {
    sku: 'SNC-DB-12W',
    name: 'Sanchay Distribution Board, 12 Way, TPN, IP42 Metal Enclosure',
    category: 'electrical',
    subcategory: 'distribution',
    brand: 'sanchay',
    seller: 'northline',
    price: 4680,
    short: 'Triple-pole-and-neutral distribution board with double door and detachable gland plate.',
    description:
      'A twelve-way TPN distribution board in a powder-coated CRCA steel enclosure with a double door — an outer hinged door and an inner detachable escutcheon that leaves only the breaker toggles accessible. Tinned copper busbars sized for 200 A, a separate earth and neutral bar, and a detachable bottom gland plate so cable entries can be drilled off site. IP42 as supplied.',
    specs: {
      current_rating_a: 200,
      poles: 4,
      voltage_v: 415,
      ip_rating: 'ip54',
      material: 'carbon_steel',
      weight_kg: 8.4,
    },
    applications: ['building_services', 'industrial_general'],
    industries: ['commercial_building', 'warehouse', 'residential'],
    tags: ['distribution board', 'db', 'tpn', '12 way', 'double door', 'busbar'],
    availability: 'in_stock',
    warrantyMonths: 24,
    certifications: ['IS 8623'],
    artwork: 'distribution-board',
    related: ['SNC-MCB-32-C', 'SNC-MCCB-100-3P', 'SNC-TRAY-300'],
  },
  {
    sku: 'SNC-TRAY-300',
    name: 'Sanchay Perforated Cable Tray, 300 mm × 50 mm, GI, 2.5 m',
    category: 'electrical',
    subcategory: 'cable-management',
    brand: 'sanchay',
    seller: 'westward-supply',
    price: 2180,
    priceUnit: 'per 2.5 m length',
    short: 'Hot-dip galvanised perforated tray for horizontal cable routing in plant rooms and ceiling voids.',
    description:
      'Perforated cable tray in 2 mm hot-dip galvanised steel, 300 mm wide with a 50 mm return. Perforations allow heat to dissipate from bunched cables, which matters because cable current ratings derate sharply when heat cannot escape. Supplied in 2.5 m lengths with coupler plates; bends, tees and reducers available as accessories. Hot-dip galvanising rather than pre-galvanised sheet is the correct choice anywhere the tray may see condensation.',
    specs: {
      material: 'galvanised_iron',
      ip_rating: 'ip20',
      weight_kg: 11.4,
    },
    applications: ['building_services', 'industrial_general'],
    industries: ['commercial_building', 'data_centre', 'manufacturing', 'infrastructure'],
    tags: ['cable tray', 'perforated', 'gi', 'hot dip', '300mm', 'cable management'],
    availability: 'in_stock',
    moq: 4,
    unit: 'length',
    warrantyMonths: 12,
    certifications: ['IS 2629'],
    artwork: 'cable-tray',
    related: ['SNC-DB-12W'],
  },
]

export const FIRE_SEEDS: ProductSeed[] = [
  {
    sku: 'PYR-SPK-PEN-68',
    name: 'Pyrocore Pendent Sprinkler, 68 °C, K80, 1/2" NPT, UL Listed',
    category: 'fire-fighting',
    subcategory: 'sprinklers',
    brand: 'pyrocore',
    seller: 'coastal-flow',
    price: 340,
    listPrice: 420,
    short: 'Standard-response pendent sprinkler with 68 °C glass bulb for ordinary hazard occupancies.',
    description:
      'A standard-response pendent sprinkler head with a 5 mm glass bulb rated 68 °C, the default selection for offices, retail and light industrial occupancies at normal ambient temperature. Bronze body with a chrome finish and a K-factor of 80, giving 80 litres per minute at 1 bar. UL listed and FM approved. Fit with the supplied escutcheon; a recessed escutcheon changes the listed spacing, so check the hydraulic design before substituting one.',
    specs: {
      temperature_rating_c: 68,
      k_factor: 80,
      response_type: 'Standard response (5 mm bulb)',
      connection_type: 'threaded',
      size_dn: 15,
      material: 'bronze',
      pressure_rating_bar: 12,
      weight_kg: 0.11,
    },
    applications: ['fire_fighting', 'building_services'],
    industries: ['commercial_building', 'warehouse', 'hospitality', 'healthcare'],
    tags: ['sprinkler', 'pendent', '68c', 'k80', 'ul listed', 'fm approved', 'glass bulb'],
    availability: 'in_stock',
    moq: 24,
    warrantyMonths: 12,
    certifications: ['UL 199', 'FM 2000', 'IS 15105'],
    artwork: 'sprinkler',
    related: ['PYR-SPK-UPR-79', 'PYR-HYD-DH-63', 'HYM-JCK-22'],
    rating: [4.6, 342],
    featured: true,
  },
  {
    sku: 'PYR-SPK-UPR-79',
    name: 'Pyrocore Upright Sprinkler, 79 °C, K115, 1/2" NPT',
    category: 'fire-fighting',
    subcategory: 'sprinklers',
    brand: 'pyrocore',
    seller: 'coastal-flow',
    price: 395,
    short: 'Upright sprinkler with higher K-factor for exposed pipework in warehouses and plant rooms.',
    description:
      'An upright sprinkler for installation on exposed distribution pipework where there is no false ceiling — warehouses, car parks, plant rooms. The 79 °C bulb suits spaces that run warmer than an air-conditioned office, and the K115 factor delivers more water per head, which is what a higher-hazard storage occupancy requires. Deflector is shaped for upright mounting and must not be installed pendent.',
    specs: {
      temperature_rating_c: 79,
      k_factor: 115,
      response_type: 'Standard response (5 mm bulb)',
      connection_type: 'threaded',
      size_dn: 15,
      material: 'bronze',
      pressure_rating_bar: 12,
      weight_kg: 0.13,
    },
    applications: ['fire_fighting', 'industrial_general'],
    industries: ['warehouse', 'manufacturing', 'infrastructure'],
    tags: ['sprinkler', 'upright', '79c', 'k115', 'warehouse', 'exposed pipework'],
    availability: 'in_stock',
    moq: 24,
    warrantyMonths: 12,
    certifications: ['UL 199', 'IS 15105'],
    artwork: 'sprinkler',
    related: ['PYR-SPK-PEN-68', 'PYR-HYD-DH-63'],
  },
  {
    sku: 'PYR-HYD-DH-63',
    name: 'Pyrocore Double Headed Hydrant Valve, 63 mm, Stainless Steel',
    category: 'fire-fighting',
    subcategory: 'hydrants',
    brand: 'pyrocore',
    seller: 'metro-industrial',
    price: 9800,
    short: 'Two-way stainless landing valve with instantaneous outlets to IS 5290, for internal hydrant risers.',
    description:
      'A double-headed landing valve for wet riser hydrant installations, with two 63 mm instantaneous female outlets and a flanged DN80 inlet. Stainless steel construction rather than the more common gunmetal, which matters on coastal sites and in car parks where the atmosphere is aggressive. Oblique-seat design keeps pressure loss low. Conforms to IS 5290 Type A; supply with blank caps and chains as standard.',
    specs: {
      connection_type: 'flanged',
      size_dn: 80,
      material: 'stainless_steel',
      pressure_rating_bar: 16,
      temperature_max_c: 80,
      weight_kg: 12.6,
    },
    applications: ['fire_fighting', 'building_services'],
    industries: ['commercial_building', 'warehouse', 'infrastructure', 'manufacturing'],
    tags: ['hydrant', 'landing valve', 'double headed', '63mm', 'is 5290', 'wet riser', 'stainless'],
    availability: 'in_stock',
    warrantyMonths: 24,
    certifications: ['IS 5290'],
    artwork: 'hydrant',
    related: ['PYR-HOSE-RRL-63', 'PYR-SPK-PEN-68', 'HYM-JCK-22'],
    rating: [4.5, 96],
  },
  {
    sku: 'PYR-HOSE-RRL-63',
    name: 'Pyrocore RRL Fire Hose, 63 mm × 15 m, Type 2, with Couplings',
    category: 'fire-fighting',
    subcategory: 'hose-reels',
    brand: 'pyrocore',
    seller: 'metro-industrial',
    price: 4250,
    priceUnit: 'per length',
    short: 'Reinforced rubber-lined hose to IS 636 Type 2, fitted with instantaneous couplings.',
    description:
      'Reinforced rubber-lined fire hose to IS 636 Type 2, 63 mm bore in a 15 m length with instantaneous male and female couplings fitted and bound. Type 2 construction has a rubber lining bonded to a circular woven polyester jacket, giving better abrasion resistance and lower friction loss than the unlined Type 1. Burst pressure 35 bar against a working pressure of 8.5 bar.',
    specs: {
      size_dn: 65,
      material: 'ppr',
      pressure_rating_bar: 8.5,
      length_m: 15,
      weight_kg: 9.2,
    },
    applications: ['fire_fighting'],
    industries: ['commercial_building', 'warehouse', 'manufacturing', 'infrastructure'],
    tags: ['fire hose', 'rrl', 'is 636', 'type 2', '63mm', '15m', 'instantaneous coupling'],
    availability: 'in_stock',
    moq: 2,
    unit: 'length',
    warrantyMonths: 12,
    certifications: ['IS 636'],
    artwork: 'hose',
    related: ['PYR-HYD-DH-63', 'PYR-SPK-PEN-68'],
  },
  {
    sku: 'PYR-FLOW-SW-100',
    name: 'Pyrocore Sprinkler Flow Switch, DN100, Vane Type',
    category: 'fire-fighting',
    subcategory: 'detection',
    brand: 'pyrocore',
    seller: 'coastal-flow',
    price: 6900,
    short: 'Paddle-type water flow detector signalling the alarm panel when a sprinkler head operates.',
    description:
      'A vane-type flow switch strapped to the sprinkler main, signalling the fire alarm panel when water moves — which is the earliest reliable indication that a head has actually operated. Includes an adjustable retard mechanism, factory set at around five seconds, to suppress false alarms from pressure surges. Two SPDT contacts, one for alarm and one for supervisory monitoring. Weatherproof enclosure suits external riser installation.',
    specs: {
      size_dn: 100,
      material: 'carbon_steel',
      pressure_rating_bar: 16,
      voltage_v: 240,
      ip_rating: 'ip65',
      weight_kg: 1.4,
    },
    applications: ['fire_fighting', 'building_services'],
    industries: ['commercial_building', 'warehouse', 'data_centre'],
    tags: ['flow switch', 'sprinkler', 'detection', 'vane', 'paddle', 'alarm', 'retard'],
    availability: 'in_stock',
    warrantyMonths: 24,
    certifications: ['UL 346'],
    artwork: 'flow-switch',
    related: ['PYR-SPK-PEN-68', 'TRU-PG-100'],
  },
]

export const INSTRUMENT_SEEDS: ProductSeed[] = [
  {
    sku: 'TRU-PG-100',
    name: 'Trumeta Pressure Gauge, 100 mm Dial, 0–16 bar, SS316 Bourdon',
    category: 'instrumentation',
    subcategory: 'pressure-gauges',
    brand: 'trumeta',
    seller: 'metro-industrial',
    price: 1450,
    listPrice: 1750,
    short: 'Glycerine-filled stainless bourdon gauge with 1/2" BSP bottom connection, accuracy class 1.0.',
    description:
      'A 100 mm dial bourdon tube pressure gauge with an SS316 wetted assembly and a glycerine-filled case. The fill damps pointer flutter from pump pulsation, which is the difference between a gauge that stays readable for years and one whose movement wears out in months. Accuracy class 1.0 across the full span, with a bottom 1/2" BSP male connection. Fit an isolating cock and siphon on steam duty.',
    specs: {
      range_bar: 16,
      accuracy_class: 'Class 1.0 (±1% FSD)',
      dial_size_mm: 100,
      connection_type: 'threaded',
      material: 'stainless_steel',
      pressure_rating_bar: 16,
      temperature_max_c: 80,
      ip_rating: 'ip65',
      weight_kg: 0.62,
    },
    applications: ['hvac', 'plumbing', 'industrial_general', 'water_treatment', 'compressed_air'],
    industries: ['commercial_building', 'manufacturing', 'process_plant'],
    tags: ['pressure gauge', 'bourdon', '100mm', 'glycerine filled', 'ss316', '0-16 bar'],
    availability: 'in_stock',
    warrantyMonths: 12,
    certifications: ['EN 837-1', 'IS 3624'],
    artwork: 'gauge',
    related: ['TRU-TG-100', 'TRU-PT-420', 'VTK-BV2S-025'],
    rating: [4.5, 267],
    featured: true,
  },
  {
    sku: 'TRU-TG-100',
    name: 'Trumeta Bimetal Thermometer, 100 mm Dial, 0–120 °C, Back Entry',
    category: 'instrumentation',
    subcategory: 'thermometers',
    brand: 'trumeta',
    seller: 'deccan-mep',
    price: 1180,
    short: 'Stainless bimetal dial thermometer with 100 mm stem, for chilled and hot water flow measurement.',
    description:
      'A bimetal coil thermometer with an all-stainless case and stem, reading 0–120 °C on a 100 mm dial. Used in pairs across a coil or heat exchanger to measure the temperature difference that actually tells you whether the equipment is performing. Always install into a thermowell rather than directly into the pipe — a direct-immersion instrument cannot be removed without draining the system.',
    specs: {
      range_bar: 0,
      accuracy_class: 'Class 1 (±1% FSD)',
      dial_size_mm: 100,
      connection_type: 'threaded',
      material: 'stainless_steel',
      temperature_max_c: 120,
      ip_rating: 'ip65',
      weight_kg: 0.34,
    },
    applications: ['hvac', 'plumbing', 'industrial_general', 'steam'],
    industries: ['commercial_building', 'manufacturing', 'healthcare'],
    tags: ['thermometer', 'bimetal', 'dial', '100mm', 'thermowell', 'temperature'],
    availability: 'in_stock',
    warrantyMonths: 12,
    certifications: ['EN 13190'],
    artwork: 'thermometer',
    related: ['TRU-PG-100', 'TRU-PT-420'],
  },
  {
    sku: 'TRU-PT-420',
    name: 'Trumeta Pressure Transmitter, 0–25 bar, 4–20 mA, 1/2" NPT',
    category: 'instrumentation',
    subcategory: 'transmitters',
    brand: 'trumeta',
    seller: 'coastal-flow',
    price: 8900,
    short: 'Two-wire piezoresistive transmitter with 0.5% accuracy for BMS and pump control feedback.',
    description:
      'A two-wire loop-powered pressure transmitter with a piezoresistive silicon sensor isolated behind a stainless diaphragm. Outputs 4–20 mA proportional to pressure, which is what a variable speed pump controller or building management system expects. Total accuracy 0.5% of span including linearity, hysteresis and repeatability. IP67 field housing with an M12 connector.',
    specs: {
      range_bar: 25,
      accuracy_class: 'Class 0.5 (±0.5% span)',
      connection_type: 'threaded',
      material: 'stainless_steel',
      voltage_v: 24,
      pressure_rating_bar: 25,
      temperature_max_c: 85,
      ip_rating: 'ip67',
      weight_kg: 0.18,
    },
    applications: ['hvac', 'water_treatment', 'industrial_general', 'building_services'],
    industries: ['data_centre', 'manufacturing', 'commercial_building', 'process_plant'],
    tags: ['pressure transmitter', '4-20ma', 'two wire', 'bms', 'piezoresistive', 'ip67'],
    availability: 'in_stock',
    warrantyMonths: 24,
    certifications: ['CE', 'EN 61326'],
    artwork: 'transmitter',
    related: ['TRU-PG-100', 'ALT-PT-HP', 'HYM-BST-VS3'],
    rating: [4.7, 63],
  },
  {
    sku: 'ALT-PT-HP',
    name: 'Altmeyer High-Accuracy Pressure Transmitter, 0–10 bar, 0.1% Class',
    category: 'instrumentation',
    subcategory: 'transmitters',
    brand: 'altmeyer',
    seller: 'coastal-flow',
    price: 46500,
    short: 'German-built reference-class transmitter with HART output for validated pharmaceutical systems.',
    description:
      'A reference-class pressure transmitter for applications where the measurement itself must be defensible — pharmaceutical utilities, calibration rigs, validated process systems. Total accuracy 0.1% of span, with a HART digital output alongside the 4–20 mA loop for configuration and diagnostics. Supplied with a factory calibration certificate traceable to national standards, and a hygienic flush diaphragm connection option.',
    specs: {
      range_bar: 10,
      accuracy_class: 'Class 0.1 (±0.1% span)',
      connection_type: 'threaded',
      material: 'stainless_steel',
      voltage_v: 24,
      pressure_rating_bar: 10,
      temperature_max_c: 100,
      ip_rating: 'ip67',
      weight_kg: 0.86,
    },
    applications: ['pharmaceutical', 'chemical', 'food_beverage', 'industrial_general'],
    industries: ['process_plant', 'healthcare', 'manufacturing'],
    tags: ['transmitter', 'high accuracy', 'hart', 'pharmaceutical', 'calibration certificate', 'imported'],
    availability: 'made_to_order',
    leadTimeDays: 28,
    warrantyMonths: 36,
    certifications: ['CE', 'ATEX', 'EN 61326'],
    artwork: 'transmitter',
    related: ['TRU-PT-420', 'ALT-FM-EM-50'],
    rating: [4.9, 19],
  },
  {
    sku: 'ALT-FM-EM-50',
    name: 'Altmeyer Electromagnetic Flow Meter, DN50, PN16 Flanged',
    category: 'instrumentation',
    subcategory: 'flow-meters',
    brand: 'altmeyer',
    seller: 'metro-industrial',
    price: 92000,
    short: 'Full-bore magmeter with no moving parts, for conductive liquids where pressure drop cannot be tolerated.',
    description:
      'An electromagnetic flow meter measures flow by the voltage a conductive liquid induces as it passes through a magnetic field. Because the bore is unobstructed there are no moving parts to wear, no pressure drop, and no sensitivity to viscosity — which is why magmeters displaced mechanical meters on water, effluent and slurry duty. PTFE liner with hastelloy electrodes, accuracy 0.3% of reading. Requires a minimum conductivity of 5 µS/cm, so it will not read demineralised water.',
    specs: {
      size_dn: 50,
      accuracy_class: 'Class 0.3 (±0.3% of reading)',
      connection_type: 'flanged',
      material: 'stainless_steel',
      voltage_v: 230,
      pressure_rating_bar: 16,
      temperature_max_c: 130,
      ip_rating: 'ip67',
      weight_kg: 8.9,
    },
    applications: ['water_treatment', 'chemical', 'industrial_general', 'food_beverage'],
    industries: ['process_plant', 'manufacturing', 'infrastructure'],
    tags: ['flow meter', 'magmeter', 'electromagnetic', 'dn50', 'ptfe liner', 'no pressure drop'],
    availability: 'made_to_order',
    leadTimeDays: 30,
    warrantyMonths: 36,
    certifications: ['CE', 'MID', 'OIML R49'],
    artwork: 'flow-meter',
    related: ['ALT-PT-HP', 'TRU-PT-420'],
    featured: true,
  },
]

export const TOOL_SEEDS: ProductSeed[] = [
  {
    sku: 'GRW-TW-200',
    name: 'Gripwell Torque Wrench, 1/2" Drive, 40–200 Nm, Calibrated',
    category: 'tools',
    subcategory: 'measuring-tools',
    brand: 'gripwell',
    seller: 'northline',
    price: 6400,
    listPrice: 7800,
    short: 'Click-type torque wrench supplied with a calibration certificate traceable to national standards.',
    description:
      'A click-type torque wrench covering 40 to 200 Nm on a 1/2 inch square drive, which spans the range most flange and structural bolting falls into. Accuracy ±3% clockwise. Supplied with a calibration certificate — a torque wrench without one is an opinion, not a measurement, and most inspection regimes will reject it. Store it wound back to its lowest setting or the spring takes a set and the calibration drifts.',
    specs: {
      drive_size: '1/2 inch square',
      torque_range_nm: 200,
      material: 'carbon_steel',
      weight_kg: 1.6,
    },
    applications: ['industrial_general', 'building_services'],
    industries: ['manufacturing', 'infrastructure', 'commercial_building'],
    tags: ['torque wrench', 'calibrated', '1/2 drive', 'click type', '40-200nm', 'certificate'],
    availability: 'in_stock',
    warrantyMonths: 12,
    certifications: ['ISO 6789'],
    artwork: 'torque-wrench',
    related: ['GRW-PW-450', 'GRW-CM-600'],
    rating: [4.6, 141],
    featured: true,
  },
  {
    sku: 'GRW-PW-450',
    name: 'Gripwell Pipe Wrench, 450 mm, Drop-Forged Steel',
    category: 'tools',
    subcategory: 'hand-tools',
    brand: 'gripwell',
    seller: 'northline',
    price: 1280,
    short: 'Heavy-duty Stillson-pattern pipe wrench with replaceable hardened jaws.',
    description:
      'A drop-forged 450 mm pipe wrench of the Stillson pattern, gripping harder as load increases because the floating jaw pivots into the work. Jaws are induction-hardened and replaceable, which extends the tool life well past the point where a cast wrench would be scrap. Handles pipe up to 60 mm outside diameter.',
    specs: {
      drive_size: 'N/A',
      material: 'carbon_steel',
      weight_kg: 2.9,
    },
    applications: ['plumbing', 'industrial_general', 'building_services'],
    industries: ['manufacturing', 'commercial_building', 'residential'],
    tags: ['pipe wrench', 'stillson', '450mm', 'drop forged', 'replaceable jaws'],
    availability: 'in_stock',
    warrantyMonths: 12,
    certifications: ['IS 4003'],
    artwork: 'wrench',
    related: ['GRW-TW-200', 'CPL-CU-22'],
    rating: [4.4, 318],
  },
  {
    sku: 'GRW-CM-600',
    name: 'Gripwell Digital Clamp Meter, 600 A AC/DC, True RMS',
    category: 'tools',
    subcategory: 'measuring-tools',
    brand: 'gripwell',
    seller: 'deccan-mep',
    price: 4850,
    short: 'True-RMS clamp meter reading AC and DC current without breaking the circuit.',
    description:
      'A 600 A true-RMS clamp meter measuring both AC and DC current via a Hall-effect sensor. True RMS matters on any circuit feeding a variable speed drive or LED lighting — an averaging meter under-reads a distorted waveform by up to 40%, which is enough to mis-diagnose a motor fault. Also measures voltage, resistance, capacitance and temperature. CAT III 600 V rated.',
    specs: {
      drive_size: 'N/A',
      current_rating_a: 600,
      voltage_v: 600,
      material: 'ppr',
      weight_kg: 0.36,
    },
    applications: ['building_services', 'industrial_general'],
    industries: ['manufacturing', 'commercial_building', 'data_centre'],
    tags: ['clamp meter', 'true rms', '600a', 'ac dc', 'cat iii', 'multimeter'],
    availability: 'in_stock',
    warrantyMonths: 24,
    certifications: ['IEC 61010', 'CAT III 600V'],
    artwork: 'clamp-meter',
    related: ['GRW-TW-200', 'SNC-MCB-32-C'],
  },
]

export const SAFETY_SEEDS: ProductSeed[] = [
  {
    sku: 'NRV-GLV-C5-L',
    name: 'Nirvaan Cut-Resistant Gloves, EN388 Level C, HPPE, Size L',
    category: 'safety',
    subcategory: 'hand-protection',
    brand: 'nirvaan',
    seller: 'westward-supply',
    price: 340,
    listPrice: 420,
    priceUnit: 'per pair',
    short: 'HPPE-blend gloves with polyurethane palm coating, EN388 cut level C for sheet metal handling.',
    description:
      'A 13-gauge HPPE and glass fibre blend liner with a polyurethane palm coating, rated cut level C to EN388:2016. That level is the practical minimum for handling sheet metal, glass and cut pipe. The PU coating gives fine grip and dexterity — an installer will actually keep these on, which is more than can be said for a heavier level-F glove. Machine washable at 40 °C without significant loss of cut resistance.',
    specs: {
      en_standard: 'EN388:2016 (4X42C)',
      cut_level: 'Level C (ISO 13997)',
      size_label: 'Large (9)',
      material: 'ppr',
      weight_kg: 0.06,
    },
    applications: ['industrial_general', 'building_services'],
    industries: ['manufacturing', 'warehouse', 'infrastructure', 'commercial_building'],
    tags: ['gloves', 'cut resistant', 'en388', 'hppe', 'level c', 'pu coated', 'size l'],
    availability: 'in_stock',
    moq: 12,
    unit: 'pair',
    warrantyMonths: 0,
    certifications: ['EN 388:2016', 'CE Cat II'],
    artwork: 'gloves',
    related: ['NRV-GLV-C5-XL', 'NRV-HLM-VNT', 'NRV-GOG-CLR'],
    rating: [4.4, 486],
    featured: true,
  },
  {
    sku: 'NRV-GLV-C5-XL',
    name: 'Nirvaan Cut-Resistant Gloves, EN388 Level C, HPPE, Size XL',
    category: 'safety',
    subcategory: 'hand-protection',
    brand: 'nirvaan',
    seller: 'westward-supply',
    price: 340,
    priceUnit: 'per pair',
    short: 'The same EN388 level C glove in extra large — stock both sizes or half the crew will not wear them.',
    description:
      'Identical construction to the Large size: 13-gauge HPPE and glass fibre liner, polyurethane palm coating, EN388 cut level C. Listed separately because glove sizing is the most common reason PPE goes unused on site — a glove that does not fit gets removed, and the injury it was meant to prevent happens anyway.',
    specs: {
      en_standard: 'EN388:2016 (4X42C)',
      cut_level: 'Level C (ISO 13997)',
      size_label: 'Extra Large (10)',
      material: 'ppr',
      weight_kg: 0.07,
    },
    applications: ['industrial_general', 'building_services'],
    industries: ['manufacturing', 'warehouse', 'infrastructure'],
    tags: ['gloves', 'cut resistant', 'en388', 'hppe', 'level c', 'size xl'],
    availability: 'in_stock',
    moq: 12,
    unit: 'pair',
    warrantyMonths: 0,
    certifications: ['EN 388:2016', 'CE Cat II'],
    artwork: 'gloves',
    related: ['NRV-GLV-C5-L'],
  },
  {
    sku: 'NRV-HLM-VNT',
    name: 'Nirvaan Safety Helmet, Vented, Ratchet Harness, EN397',
    category: 'safety',
    subcategory: 'head-eye',
    brand: 'nirvaan',
    seller: 'deccan-mep',
    price: 620,
    short: 'ABS shell helmet with six-point ratchet harness and side vents for hot-climate site work.',
    description:
      'An ABS shell industrial safety helmet certified to EN397 with a six-point textile harness and a ratchet adjuster. The side vents make a measurable difference to whether it stays on the head through an Indian summer afternoon, which is the entire point. Includes a sweatband, chinstrap anchor points and slots for ear defenders and a visor. Replace after any impact, and in any case within five years of the moulding date stamped inside the peak.',
    specs: {
      en_standard: 'EN 397:2012',
      size_label: 'Universal (53–63 cm)',
      material: 'ppr',
      ip_rating: 'ip20',
      weight_kg: 0.36,
    },
    applications: ['industrial_general', 'building_services'],
    industries: ['infrastructure', 'manufacturing', 'warehouse', 'commercial_building'],
    tags: ['helmet', 'hard hat', 'en397', 'vented', 'ratchet', 'abs', 'ppe'],
    availability: 'in_stock',
    moq: 10,
    warrantyMonths: 0,
    certifications: ['EN 397:2012', 'IS 2925'],
    artwork: 'helmet',
    related: ['NRV-GOG-CLR', 'NRV-GLV-C5-L', 'NRV-HRN-2PT'],
    rating: [4.3, 372],
  },
  {
    sku: 'NRV-GOG-CLR',
    name: 'Nirvaan Safety Goggles, Clear Anti-Fog, EN166 1B',
    category: 'safety',
    subcategory: 'head-eye',
    brand: 'nirvaan',
    seller: 'deccan-mep',
    price: 285,
    short: 'Indirect-vent goggles with anti-fog coating and 1B impact rating, worn over prescription glasses.',
    description:
      'Indirect-vented polycarbonate goggles rated EN166 1B — optical class 1, medium-energy impact. The indirect venting keeps liquid splash out while still allowing airflow, and the anti-fog coating is on the inside surface where it actually helps. The frame clears most prescription spectacles, which removes the usual excuse for not wearing eye protection at all.',
    specs: {
      en_standard: 'EN 166:2001 (1B 3 4)',
      size_label: 'Universal',
      material: 'ppr',
      weight_kg: 0.08,
    },
    applications: ['industrial_general', 'chemical', 'building_services'],
    industries: ['manufacturing', 'process_plant', 'infrastructure'],
    tags: ['goggles', 'eye protection', 'en166', 'anti-fog', 'indirect vent', 'over-spectacle'],
    availability: 'in_stock',
    moq: 12,
    warrantyMonths: 0,
    certifications: ['EN 166:2001'],
    artwork: 'goggles',
    related: ['NRV-HLM-VNT', 'NRV-GLV-C5-L'],
  },
  {
    sku: 'NRV-HRN-2PT',
    name: 'Nirvaan Full Body Harness, Two-Point, EN361 with Shock Lanyard',
    category: 'safety',
    subcategory: 'height-safety',
    brand: 'nirvaan',
    seller: 'northline',
    price: 3450,
    short: 'Two-point fall-arrest harness with energy-absorbing lanyard and scaffold hooks, EN361 certified.',
    description:
      'A full body fall-arrest harness with front and rear attachment points, supplied with a 1.8 m energy-absorbing lanyard and two scaffold hooks. The energy absorber is the part that matters: it limits arrest force to under 6 kN, which is the difference between being stopped and being injured by being stopped. Check the clearance below the anchor before use — a 1.8 m lanyard with a deployed absorber needs roughly 6.5 m of free fall distance.',
    specs: {
      en_standard: 'EN 361 / EN 355 / EN 362',
      size_label: 'Universal (adjustable)',
      material: 'ppr',
      weight_kg: 1.9,
    },
    applications: ['industrial_general', 'building_services'],
    industries: ['infrastructure', 'manufacturing', 'commercial_building', 'warehouse'],
    tags: ['harness', 'fall arrest', 'height safety', 'en361', 'shock absorbing lanyard', 'scaffold hook'],
    availability: 'in_stock',
    warrantyMonths: 12,
    certifications: ['EN 361', 'EN 355', 'CE Cat III'],
    artwork: 'harness',
    related: ['NRV-HLM-VNT', 'NRV-GLV-C5-L'],
    rating: [4.6, 118],
  },
]
