import type { ProductSeed } from '../build-product'

/**
 * Valves & flow control.
 *
 * This category is deliberately the densest in the catalogue. The canonical
 * demo query — "stainless steel threaded valve for an HVAC system under
 * ₹5,000" — has to return a credible result set, which means it also needs
 * credible *near misses*: brass instead of stainless, flanged instead of
 * threaded, DN65 that busts the budget by a few hundred rupees. A ranking
 * engine with nothing to discriminate between proves nothing.
 */

export const VALVE_SEEDS: ProductSeed[] = [
  /* ---------------------------------------------------------------- exact */
  {
    sku: 'VTK-BV2S-050',
    name: 'Vantek 2-Piece Ball Valve, SS316, DN50 Threaded',
    category: 'valves',
    subcategory: 'ball-valves',
    brand: 'vantek',
    seller: 'metro-industrial',
    price: 3820,
    listPrice: 4450,
    short: 'Full-bore SS316 isolation valve with BSP female threads, rated PN63 for chilled and hot water service.',
    description:
      'A full-bore two-piece ball valve investment cast in SS316, intended for isolation duty on chilled water, hot water and general utility lines. The blowout-proof stem carries a PTFE packing set with a live-loaded gland, so the valve holds its seal through the thermal cycling typical of a commercial HVAC riser. Seats are reinforced PTFE. Supplied with a vinyl-sleeved lever handle and a locking plate for lockout-tagout. BSP parallel female threads to IS 554 as standard; NPT available to order.',
    specs: {
      valve_type: 'ball',
      material: 'stainless_steel',
      connection_type: 'threaded',
      size_dn: 50,
      pressure_rating_bar: 63,
      temperature_max_c: 200,
      operation: 'manual_lever',
      seat_material: 'Reinforced PTFE',
      weight_kg: 2.4,
    },
    applications: ['hvac', 'plumbing', 'building_services', 'industrial_general'],
    industries: ['commercial_building', 'data_centre', 'hospitality'],
    tags: ['ball valve', 'ss316', 'threaded', 'full bore', 'isolation', 'chilled water'],
    availability: 'in_stock',
    warrantyMonths: 24,
    certifications: ['IS 554', 'CE'],
    artwork: 'ball-valve',
    related: ['VTK-BV3S-050', 'VTK-YS-050T', 'VTK-CV-050T', 'DOR-BV-050T'],
    rating: [4.6, 148],
    featured: true,
  },
  {
    sku: 'VTK-BV2S-040',
    name: 'Vantek 2-Piece Ball Valve, SS316, DN40 Threaded',
    category: 'valves',
    subcategory: 'ball-valves',
    brand: 'vantek',
    seller: 'metro-industrial',
    price: 2940,
    listPrice: 3400,
    short: 'DN40 full-bore stainless isolation valve, same PN63 body as the DN50 with a lighter lever.',
    description:
      'The DN40 variant of Vantek’s full-bore two-piece stainless range. Identical SS316 body casting, PTFE seat and live-loaded gland to the DN50, sized for branch isolation and fan coil connections where a DN50 valve is oversized. Widely used on chilled water branches serving individual floors.',
    specs: {
      valve_type: 'ball',
      material: 'stainless_steel',
      connection_type: 'threaded',
      size_dn: 40,
      pressure_rating_bar: 63,
      temperature_max_c: 200,
      operation: 'manual_lever',
      seat_material: 'Reinforced PTFE',
      weight_kg: 1.7,
    },
    applications: ['hvac', 'plumbing', 'building_services'],
    industries: ['commercial_building', 'hospitality', 'healthcare'],
    tags: ['ball valve', 'ss316', 'threaded', 'branch isolation'],
    availability: 'in_stock',
    warrantyMonths: 24,
    certifications: ['IS 554', 'CE'],
    artwork: 'ball-valve',
    related: ['VTK-BV2S-050', 'VTK-BV2S-025'],
  },
  {
    sku: 'VTK-BV3S-050',
    name: 'Vantek 3-Piece Ball Valve, SS316, DN50 Threaded',
    category: 'valves',
    subcategory: 'ball-valves',
    brand: 'vantek',
    seller: 'metro-industrial',
    price: 4680,
    short: 'Three-piece body allows in-line servicing without breaking the pipework — preferred on maintained plant.',
    description:
      'A three-piece SS316 ball valve whose centre section can be removed for seat and seal replacement without disturbing the connecting pipework. That single property makes it the standard choice on plant rooms where isolation valves are expected to be serviced rather than replaced. Swing-out body, PTFE seats, blowout-proof stem, and a ISO 5211 direct-mount pad for later actuation.',
    specs: {
      valve_type: 'ball',
      material: 'stainless_steel',
      connection_type: 'threaded',
      size_dn: 50,
      pressure_rating_bar: 63,
      temperature_max_c: 220,
      operation: 'manual_lever',
      seat_material: 'Reinforced PTFE',
      weight_kg: 3.1,
    },
    applications: ['hvac', 'industrial_general', 'chemical', 'building_services'],
    industries: ['commercial_building', 'manufacturing', 'process_plant'],
    tags: ['ball valve', 'ss316', 'three piece', 'serviceable', 'iso 5211'],
    availability: 'in_stock',
    warrantyMonths: 36,
    certifications: ['IS 554', 'CE', 'ISO 5211'],
    artwork: 'ball-valve',
    related: ['VTK-BV2S-050', 'DOR-MCV-050'],
    rating: [4.7, 92],
    featured: true,
  },
  {
    sku: 'DOR-BV-050T',
    name: 'Dorsett Series 40 Ball Valve, SS316, DN50 Threaded',
    category: 'valves',
    subcategory: 'ball-valves',
    brand: 'dorsett',
    seller: 'coastal-flow',
    price: 4950,
    short: 'UK-manufactured stainless ball valve with anti-static stem and fire-safe seat option.',
    description:
      'Dorsett’s Series 40 is specified where a valve has to satisfy a third-party inspection regime as well as a duty. The stem carries an anti-static device continuously earthing ball to body, and the graphite-backed seat carries an API 607 fire-safe qualification. Body and ball are both SS316. Common on data centre and pharmaceutical chilled water where the specification is written to European standards.',
    specs: {
      valve_type: 'ball',
      material: 'stainless_steel',
      connection_type: 'threaded',
      size_dn: 50,
      pressure_rating_bar: 64,
      temperature_max_c: 230,
      operation: 'manual_lever',
      seat_material: 'Graphite-backed PTFE',
      weight_kg: 2.6,
    },
    applications: ['hvac', 'pharmaceutical', 'chemical', 'building_services'],
    industries: ['data_centre', 'healthcare', 'process_plant'],
    tags: ['ball valve', 'ss316', 'fire safe', 'anti-static', 'api 607', 'imported'],
    availability: 'low_stock',
    warrantyMonths: 36,
    certifications: ['API 607', 'CE', 'PED 2014/68/EU'],
    artwork: 'ball-valve',
    related: ['VTK-BV2S-050', 'DOR-DRV-050'],
    rating: [4.8, 61],
  },
  {
    sku: 'VTK-BV2S-025',
    name: 'Vantek 2-Piece Ball Valve, SS304, DN25 Threaded',
    category: 'valves',
    subcategory: 'ball-valves',
    brand: 'vantek',
    seller: 'deccan-mep',
    price: 1650,
    listPrice: 1980,
    short: 'Compact DN25 stainless isolation valve for equipment tap-offs and instrument lines.',
    description:
      'SS304 two-piece ball valve for small-bore isolation — gauge tappings, drain points, make-up water lines and equipment connections. Same construction as the larger Vantek range in a lower grade of stainless suited to closed-circuit water rather than aggressive media.',
    specs: {
      valve_type: 'ball',
      material: 'stainless_steel',
      connection_type: 'threaded',
      size_dn: 25,
      pressure_rating_bar: 40,
      temperature_max_c: 180,
      operation: 'manual_lever',
      seat_material: 'PTFE',
      weight_kg: 0.6,
    },
    applications: ['hvac', 'plumbing', 'building_services', 'compressed_air'],
    industries: ['commercial_building', 'residential', 'manufacturing'],
    tags: ['ball valve', 'ss304', 'threaded', 'small bore', 'drain point'],
    availability: 'in_stock',
    warrantyMonths: 18,
    certifications: ['IS 554'],
    artwork: 'ball-valve',
    related: ['VTK-BV2S-040', 'TRU-PG-100'],
  },
  {
    sku: 'VTK-BV2S-065',
    name: 'Vantek 2-Piece Ball Valve, SS316, DN65 Threaded',
    category: 'valves',
    subcategory: 'ball-valves',
    brand: 'vantek',
    seller: 'metro-industrial',
    price: 5450,
    short: 'DN65 full-bore stainless isolation valve — the largest size still practical in a threaded pattern.',
    description:
      'At DN65 a threaded valve is at the upper limit of what an installer can reasonably make up on site, and most specifications move to flanged above this size. Where the pipework is already threaded, this valve avoids a transition. Full-bore SS316 body, reinforced PTFE seats, extended lever for the higher operating torque.',
    specs: {
      valve_type: 'ball',
      material: 'stainless_steel',
      connection_type: 'threaded',
      size_dn: 65,
      pressure_rating_bar: 63,
      temperature_max_c: 200,
      operation: 'manual_lever',
      seat_material: 'Reinforced PTFE',
      weight_kg: 4.2,
    },
    applications: ['hvac', 'industrial_general', 'building_services'],
    industries: ['commercial_building', 'manufacturing'],
    tags: ['ball valve', 'ss316', 'threaded', 'dn65', 'full bore'],
    availability: 'in_stock',
    warrantyMonths: 24,
    certifications: ['IS 554', 'CE'],
    artwork: 'ball-valve',
    related: ['VTK-BV2S-050', 'VTK-GV-080F'],
  },

  /* ------------------------------------------------- material near-misses */
  {
    sku: 'VTK-BVB-050',
    name: 'Vantek Ball Valve, Forged Brass, DN50 Threaded',
    category: 'valves',
    subcategory: 'ball-valves',
    brand: 'vantek',
    seller: 'northline',
    price: 1480,
    listPrice: 1850,
    short: 'Economical forged brass isolation valve for potable and low-pressure utility water.',
    description:
      'Forged brass body with a hard chrome-plated ball, intended for potable water, low-pressure utility and general plumbing isolation. Considerably cheaper than stainless, and entirely adequate where the medium is clean domestic water. Not recommended for chilled water systems dosed with glycol inhibitors, which attack brass over time.',
    specs: {
      valve_type: 'ball',
      material: 'brass',
      connection_type: 'threaded',
      size_dn: 50,
      pressure_rating_bar: 25,
      temperature_max_c: 110,
      operation: 'manual_lever',
      seat_material: 'PTFE',
      weight_kg: 1.4,
    },
    applications: ['plumbing', 'building_services', 'irrigation'],
    industries: ['residential', 'commercial_building'],
    tags: ['ball valve', 'brass', 'threaded', 'potable water', 'economy'],
    availability: 'in_stock',
    warrantyMonths: 12,
    certifications: ['IS 6157'],
    artwork: 'ball-valve',
    related: ['VTK-BV2S-050', 'CPL-CPVC-BV-050'],
    rating: [4.1, 213],
  },

  /* ------------------------------------------------ connection near-misses */
  {
    sku: 'DOR-BFV-100',
    name: 'Dorsett Butterfly Valve, Ductile Iron, DN100 Wafer',
    category: 'valves',
    subcategory: 'butterfly-valves',
    brand: 'dorsett',
    seller: 'coastal-flow',
    price: 6400,
    short: 'Wafer-pattern butterfly valve with SS316 disc and EPDM liner for large-bore chilled water isolation.',
    description:
      'Above DN80, butterfly valves displace ball valves on cost and weight. This wafer-pattern valve has a ductile iron body, an SS316 disc and a replaceable EPDM liner that forms both the seat and the flange gasket, so no separate gasket is required. Ten-position lever as standard; gearbox operation recommended from DN150 upward.',
    specs: {
      valve_type: 'butterfly',
      material: 'ductile_iron',
      connection_type: 'wafer',
      size_dn: 100,
      pressure_rating_bar: 16,
      temperature_max_c: 120,
      operation: 'manual_lever',
      seat_material: 'EPDM liner',
      weight_kg: 5.8,
    },
    applications: ['hvac', 'plumbing', 'water_treatment', 'building_services'],
    industries: ['commercial_building', 'data_centre', 'infrastructure'],
    tags: ['butterfly valve', 'wafer', 'ductile iron', 'epdm', 'large bore'],
    availability: 'in_stock',
    warrantyMonths: 24,
    certifications: ['EN 593', 'CE'],
    artwork: 'butterfly-valve',
    related: ['VTK-GV-080F', 'DOR-DRV-050'],
    rating: [4.5, 77],
    featured: true,
  },
  {
    sku: 'VTK-GV-080F',
    name: 'Vantek Gate Valve, Cast Iron, DN80 Flanged PN16',
    category: 'valves',
    subcategory: 'ball-valves',
    brand: 'vantek',
    seller: 'northline',
    price: 5900,
    short: 'Rising-stem cast iron gate valve for infrequent isolation on large-bore water mains.',
    description:
      'A traditional rising-stem gate valve for duties where the valve is opened once at commissioning and closed only for maintenance. Cast iron body to IS 210, bronze trim, and a bolted bonnet with a graphite packing set. Gate valves offer near-zero pressure drop when fully open, which is why they persist on pump suction and main risers despite being slow to operate.',
    specs: {
      valve_type: 'gate',
      material: 'cast_iron',
      connection_type: 'flanged',
      size_dn: 80,
      pressure_rating_bar: 16,
      temperature_max_c: 120,
      operation: 'manual_gear',
      seat_material: 'Bronze',
      weight_kg: 21,
    },
    applications: ['plumbing', 'water_treatment', 'fire_fighting', 'building_services'],
    industries: ['infrastructure', 'commercial_building', 'manufacturing'],
    tags: ['gate valve', 'cast iron', 'flanged', 'pn16', 'rising stem'],
    availability: 'in_stock',
    warrantyMonths: 24,
    certifications: ['IS 14846', 'IS 210'],
    artwork: 'gate-valve',
    related: ['DOR-BFV-100', 'VTK-CV-050T'],
  },

  /* --------------------------------------------------------- other types */
  {
    sku: 'VTK-CV-050T',
    name: 'Vantek Check Valve, SS316, DN50 Threaded',
    category: 'valves',
    subcategory: 'check-valves',
    brand: 'vantek',
    seller: 'metro-industrial',
    price: 3150,
    short: 'Spring-loaded stainless non-return valve preventing reverse flow on pump discharge.',
    description:
      'A spring-assisted disc check valve in SS316, installed on pump discharge to stop reverse flow when the pump stops. The spring closes the disc before flow reverses, which is what prevents the water hammer a swing check produces on a tall riser. Horizontal or vertical mounting. Cracking pressure 0.2 bar.',
    specs: {
      valve_type: 'check',
      material: 'stainless_steel',
      connection_type: 'threaded',
      size_dn: 50,
      pressure_rating_bar: 40,
      temperature_max_c: 180,
      seat_material: 'PTFE',
      weight_kg: 1.9,
    },
    applications: ['hvac', 'plumbing', 'fire_fighting', 'building_services'],
    industries: ['commercial_building', 'manufacturing', 'healthcare'],
    tags: ['check valve', 'nrv', 'non return', 'ss316', 'threaded', 'pump discharge'],
    availability: 'in_stock',
    warrantyMonths: 24,
    certifications: ['IS 5312'],
    artwork: 'check-valve',
    related: ['VTK-BV2S-050', 'HYM-CP-ES-050'],
    rating: [4.5, 118],
  },
  {
    sku: 'VTK-YS-050T',
    name: 'Vantek Y-Strainer, SS316, DN50 Threaded, 40 Mesh',
    category: 'valves',
    subcategory: 'strainers',
    brand: 'vantek',
    seller: 'metro-industrial',
    price: 2780,
    short: 'Inline stainless strainer protecting pumps, coils and control valves from pipeline debris.',
    description:
      'A Y-pattern strainer with a 40-mesh SS316 screen, fitted upstream of pumps, control valves and heat exchanger coils to catch weld slag, scale and construction debris. The blow-down plug allows the screen to be flushed without removing the strainer from the line. Screen mesh from 20 to 100 available; 40 mesh is the usual choice for closed-circuit chilled water.',
    specs: {
      valve_type: 'strainer',
      material: 'stainless_steel',
      connection_type: 'threaded',
      size_dn: 50,
      pressure_rating_bar: 40,
      temperature_max_c: 200,
      seat_material: 'SS316 mesh',
      weight_kg: 2.1,
    },
    applications: ['hvac', 'plumbing', 'industrial_general', 'building_services'],
    industries: ['commercial_building', 'data_centre', 'manufacturing'],
    tags: ['strainer', 'y-strainer', 'ss316', 'threaded', 'coil protection', '40 mesh'],
    availability: 'in_stock',
    warrantyMonths: 18,
    certifications: ['IS 554'],
    artwork: 'strainer',
    related: ['VTK-BV2S-050', 'VTK-CV-050T', 'DOR-DRV-050'],
  },
  {
    sku: 'DOR-DRV-050',
    name: 'Dorsett Double Regulating Valve, Bronze, DN50 Threaded',
    category: 'valves',
    subcategory: 'control-valves',
    brand: 'dorsett',
    seller: 'coastal-flow',
    price: 7850,
    short: 'Commissioning valve with fixed memory stop and pressure test points for hydronic balancing.',
    description:
      'A double regulating valve is what makes a hydronic system balance. The valve sets a design flow rate at commissioning and then keeps a mechanical memory of that position, so it can be closed for isolation and reopened to exactly the same setting. Bronze body, two pressure test points with self-sealing valves, and a calibrated position indicator readable against the published flow charts.',
    specs: {
      valve_type: 'balancing',
      material: 'bronze',
      connection_type: 'threaded',
      size_dn: 50,
      pressure_rating_bar: 25,
      temperature_max_c: 120,
      operation: 'manual_gear',
      seat_material: 'EPDM',
      weight_kg: 3.4,
    },
    applications: ['hvac', 'building_services'],
    industries: ['commercial_building', 'data_centre', 'hospitality', 'healthcare'],
    tags: ['balancing valve', 'drv', 'commissioning', 'bronze', 'test points', 'hydronic'],
    availability: 'in_stock',
    warrantyMonths: 36,
    certifications: ['BS 7350', 'CE'],
    artwork: 'balancing-valve',
    related: ['DOR-MCV-050', 'VTK-YS-050T', 'DOR-BV-050T'],
    rating: [4.7, 54],
    featured: true,
  },
  {
    sku: 'DOR-MCV-050',
    name: 'Dorsett 2-Way Motorised Control Valve, DN50, 24V Modulating',
    category: 'valves',
    subcategory: 'control-valves',
    brand: 'dorsett',
    seller: 'coastal-flow',
    price: 18900,
    short: 'Modulating control valve with 24V actuator and 0–10V BMS input for coil temperature control.',
    description:
      'A two-way modulating control valve assembly for chilled or hot water coil control under a building management system. The 24V actuator accepts a 0–10 V or 4–20 mA signal and drives an equal-percentage characterised plug, so coil output tracks the control signal linearly rather than dumping most of its authority in the first 20% of travel. Includes manual override and a position feedback signal.',
    specs: {
      valve_type: 'motorised',
      material: 'bronze',
      connection_type: 'threaded',
      size_dn: 50,
      pressure_rating_bar: 16,
      temperature_max_c: 120,
      operation: 'electric_actuator',
      voltage_v: 24,
      seat_material: 'EPDM',
      weight_kg: 4.6,
    },
    applications: ['hvac', 'building_services'],
    industries: ['commercial_building', 'data_centre', 'healthcare'],
    tags: ['control valve', 'motorised', 'modulating', 'bms', '24v', '0-10v', 'coil control'],
    availability: 'made_to_order',
    leadTimeDays: 21,
    warrantyMonths: 24,
    certifications: ['CE', 'EN 60730'],
    artwork: 'control-valve',
    related: ['DOR-DRV-050', 'AFX-FCU-600'],
    rating: [4.6, 38],
  },
  {
    sku: 'DOR-PRV-050',
    name: 'Dorsett Pressure Reducing Valve, Bronze, DN50 Threaded',
    category: 'valves',
    subcategory: 'control-valves',
    brand: 'dorsett',
    seller: 'westward-supply',
    price: 9200,
    short: 'Direct-acting pressure reducing valve holding a stable downstream set point from 1.5 to 6 bar.',
    description:
      'A direct-acting diaphragm PRV that holds a constant downstream pressure regardless of upstream fluctuation, protecting fixtures and equipment on the lower floors of a tall building. Bronze body, stainless trim, adjustable set point between 1.5 and 6 bar. Fit a strainer upstream — debris on the seat is the single most common cause of a PRV failing to hold set point.',
    specs: {
      valve_type: 'pressure_reducing',
      material: 'bronze',
      connection_type: 'threaded',
      size_dn: 50,
      pressure_rating_bar: 25,
      temperature_max_c: 80,
      operation: 'automatic',
      seat_material: 'NBR',
      weight_kg: 5.2,
    },
    applications: ['plumbing', 'building_services', 'fire_fighting'],
    industries: ['commercial_building', 'residential', 'hospitality'],
    tags: ['prv', 'pressure reducing', 'bronze', 'threaded', 'set point'],
    availability: 'low_stock',
    warrantyMonths: 24,
    certifications: ['EN 1567', 'CE'],
    artwork: 'control-valve',
    related: ['VTK-YS-050T', 'TRU-PG-100'],
  },
]
