import type { Metadata } from 'next'
import Link from 'next/link'
import { ChevronRight, FileText, Search, Sparkles } from 'lucide-react'
import { getCatalogRepository } from '@/server/repositories'
import { buildComparisonRows } from '@/server/catalog/comparison'
import { getAiProvider } from '@/server/ai/provider'
import { MAX_COMPARE, MIN_COMPARE } from '@/lib/compare'
import { CompareHydrate } from '@/components/catalog/compare-hydrate'
import { ComparisonGrid } from '@/components/catalog/comparison-grid'
import { EmptyComparisonState } from '@/components/ui/states'
import { ButtonLink } from '@/components/ui/button'
import { pluralize } from '@/lib/format'

export const metadata: Metadata = {
  title: 'Compare products',
  description:
    'Line up to four industrial products side by side — full specification sheets, with a written summary of where they actually differ.',
  robots: { index: false, follow: true },
}

/**
 * Product comparison.
 *
 * Driven by `?ids=` so a comparison is shareable. Anyone arriving from the
 * floating tray has ids in `localStorage` instead, and `<CompareHydrate />`
 * promotes those into the URL on mount.
 *
 * The trade-off summary is generated by the AI provider from the real
 * specification sheets — and it is told not to declare a winner, because in
 * procurement the cheapest that meets the spec and the one that survives being
 * serviced are answers to different questions.
 */
export default async function ComparePage({
  searchParams,
}: {
  searchParams: Promise<{ ids?: string }>
}) {
  const { ids } = await searchParams

  const requested = (ids ?? '')
    .split(',')
    .map((id) => id.trim())
    .filter(Boolean)
    .slice(0, MAX_COMPARE)

  const products =
    requested.length > 0
      ? await getCatalogRepository().findManyByIds(requested)
      : []

  const rows = products.length >= MIN_COMPARE ? buildComparisonRows(products) : []
  const summary =
    products.length >= MIN_COMPARE ? await getAiProvider().compare(products) : null

  return (
    <div className="container-page py-8 lg:py-12">
      <nav aria-label="Breadcrumb" className="mb-5">
        <ol className="flex items-center gap-1.5 text-[13px] text-muted">
          <li>
            <Link href="/" className="hover:text-text">
              Home
            </Link>
          </li>
          <ChevronRight className="size-3.5 text-faint" aria-hidden />
          <li>
            <Link href="/products" className="hover:text-text">
              Products
            </Link>
          </li>
          <ChevronRight className="size-3.5 text-faint" aria-hidden />
          <li aria-current="page" className="text-text">
            Compare
          </li>
        </ol>
      </nav>

      <div className="mb-8 flex flex-col gap-5 md:flex-row md:items-end md:justify-between">
        <div className="max-w-2xl">
          <h1 className="font-display text-3xl leading-tight font-semibold tracking-tight md:text-4xl">
            Compare products
          </h1>
          <p className="mt-3 text-[15px] leading-relaxed text-muted">
            {products.length >= MIN_COMPARE
              ? `${pluralize(products.length, 'product')} side by side. Rows where all of them agree are dimmed — the differences are what is left.`
              : `Pick two to four products and their specification sheets line up here, with a written summary of where they actually differ.`}
          </p>
        </div>

        {products.length >= MIN_COMPARE && (
          <div className="flex flex-wrap gap-2">
            <ButtonLink
              href="/products"
              variant="secondary"
              leadingIcon={<Search className="size-4" aria-hidden />}
            >
              Add another
            </ButtonLink>
            <ButtonLink
              href={`/account/rfq/new?product=${products.map((p) => p.id).join(',')}`}
              leadingIcon={<FileText className="size-4" aria-hidden />}
            >
              Quote all {products.length}
            </ButtonLink>
          </div>
        )}
      </div>

      {/* Restore from the tray when the URL is bare. */}
      <CompareHydrate hasIds={requested.length > 0} />

      {products.length === 0 ? (
        <EmptyComparisonState />
      ) : products.length === 1 ? (
        <div className="rounded-xl border border-dashed border-border bg-surface/50 px-6 py-14 text-center">
          <h2 className="font-display text-lg font-semibold text-text">
            One product is not a comparison
          </h2>
          <p className="mx-auto mt-2 max-w-md text-sm leading-relaxed text-muted">
            You have <span className="text-text">{products[0]?.name}</span> selected.
            Add at least one more and the specification sheets line up side by side.
          </p>
          <div className="mt-6 flex flex-wrap items-center justify-center gap-2.5">
            <ButtonLink href="/products" size="sm">
              Find something to compare it with
            </ButtonLink>
            <ButtonLink href="/assistant" size="sm" variant="secondary">
              Ask the assistant
            </ButtonLink>
          </div>
        </div>
      ) : (
        <>
          {/* Trade-off summary --------------------------------------------- */}
          {summary && (
            <section
              aria-labelledby="summary-heading"
              className="mb-6 flex gap-3.5 rounded-xl border border-accent-line bg-accent-soft/40 p-5"
            >
              <span
                className="grid size-9 shrink-0 place-items-center rounded-full border border-accent-line bg-surface text-accent-text"
                aria-hidden
              >
                <Sparkles className="size-4" />
              </span>
              <div className="min-w-0">
                <h2
                  id="summary-heading"
                  className="text-[11px] font-semibold tracking-wide text-accent-text uppercase"
                >
                  Where these differ
                </h2>
                <p className="mt-1.5 text-[14px] leading-relaxed text-text-2">{summary}</p>
              </div>
            </section>
          )}

          <ComparisonGrid products={products} rows={rows} />

          <div className="mt-8 flex flex-col items-center gap-3 rounded-xl border border-dashed border-border bg-surface/50 px-6 py-8 text-center">
            <p className="max-w-lg text-sm leading-relaxed text-muted">
              Send one quotation request covering all of them. Suppliers quote
              against your quantities, and you compare real prices rather than
              list rates.
            </p>
            <ButtonLink
              href={`/account/rfq/new?product=${products.map((p) => p.id).join(',')}`}
              size="sm"
              leadingIcon={<FileText className="size-4" aria-hidden />}
            >
              Request quotations
            </ButtonLink>
          </div>
        </>
      )}
    </div>
  )
}
