import Link from 'next/link'
import {
  ArrowRight,
  Bookmark,
  Clock,
  FileText,
  Search,
  Sparkles,
  TrendingUp,
} from 'lucide-react'
import type { Metadata } from 'next'
import { requireUser } from '@/server/auth/session'
import { getActivityRepository, getCatalogRepository } from '@/server/repositories'
import { highlightSpecs } from '@/server/catalog/highlights'
import { parseIntentOffline } from '@/server/ai/intent-offline'
import {
  formatPrice,
  formatRelative,
  pluralize,
  RFQ_TONE,
} from '@/lib/format'
import { RFQ_STATUS_LABELS } from '@/lib/domain/account'
import { Badge } from '@/components/ui/badge'
import { ButtonLink } from '@/components/ui/button'
import { StateBlock } from '@/components/ui/states'
import { MatchBadge } from '@/components/ui/match-score'
import { ProductCard } from '@/components/catalog/product-card'
import { BarChart, PageHeader, SectionCard, ShareBar, StatCard } from '@/components/account/ui'

export const metadata: Metadata = { title: 'Dashboard' }

/**
 * Customer dashboard.
 *
 * Answers three questions in order: what is waiting on me, what was I doing,
 * and what should I look at next. Recommendations are generated by replaying
 * the buyer's most recent search through the live ranking engine rather than
 * by a separate recommendation model — the ranking they already saw is the
 * best available signal, and reusing it means one system to reason about.
 */
export default async function AccountDashboard({
  searchParams,
}: {
  searchParams: Promise<{ welcome?: string }>
}) {
  const [{ welcome }, user] = await Promise.all([searchParams, requireUser('/account')])

  const activity = getActivityRepository()
  const catalog = getCatalogRepository()

  const [saved, rfqs, searches, recentIds, notifications, conversations] = await Promise.all([
    activity.listSavedProducts(user.id),
    activity.listRfqs(user.id),
    activity.listSearchHistory(user.id, 30),
    activity.recentlyViewed(user.id, 6),
    activity.listNotifications(user.id, 5),
    activity.listConversations(user.id, 3),
  ])

  const [savedProducts, recentProducts] = await Promise.all([
    catalog.findManyByIds(saved.slice(0, 4).map((entry) => entry.productId)),
    catalog.findManyByIds(recentIds),
  ])

  /* --- Recommendations: replay the latest search through the engine ------ */
  const latestSearch = searches[0]
  const recommended = latestSearch
    ? (await catalog.rankByIntent(parseIntentOffline(latestSearch.query), 8)).results
        .filter((result) => !saved.some((entry) => entry.productId === result.product.id))
        .slice(0, 3)
    : []

  /* --- Activity chart: searches per day over the last week --------------- */
  const DAY_LABELS = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat']
  const today = new Date()
  const week = Array.from({ length: 7 }, (_, offset) => {
    const date = new Date(today)
    date.setDate(today.getDate() - (6 - offset))
    const key = date.toISOString().slice(0, 10)
    return {
      label: key,
      short: DAY_LABELS[date.getDay()] ?? '',
      value: searches.filter((event) => event.createdAt.slice(0, 10) === key).length,
    }
  })

  const aiSearches = searches.filter((event) => event.mode === 'ai').length
  const openRfqs = rfqs.filter(
    (rfq) => !['accepted', 'declined', 'expired'].includes(rfq.status)
  )
  const quotedRfqs = rfqs.filter((rfq) => rfq.status === 'quoted')
  const unread = notifications.filter((entry) => !entry.read)

  return (
    <>
      <PageHeader
        title={`${greeting()}, ${user.name.split(' ')[0]}`}
        description={
          welcome
            ? 'Your account is ready. Describe a requirement to the assistant and it will rank the catalogue against it.'
            : 'Here is where your sourcing stands today.'
        }
        action={
          <ButtonLink href="/assistant" leadingIcon={<Sparkles className="size-4" aria-hidden />}>
            New requirement
          </ButtonLink>
        }
      />

      {/* Attention ------------------------------------------------------- */}
      {quotedRfqs.length > 0 && (
        <div className="mb-6 flex flex-col gap-3 rounded-xl border border-accent-line bg-accent-soft/50 p-4 sm:flex-row sm:items-center">
          <FileText className="size-5 shrink-0 text-accent-text" aria-hidden />
          <div className="min-w-0 flex-1">
            <p className="text-sm font-semibold text-text">
              {pluralize(quotedRfqs.length, 'quotation')} waiting on you
            </p>
            <p className="mt-0.5 text-[13px] text-muted">
              {quotedRfqs[0]?.reference}
              {quotedRfqs[0]?.quotedTotal != null &&
                ` — ${formatPrice(quotedRfqs[0].quotedTotal)} total`}
              {quotedRfqs[0]?.validUntil &&
                `, valid until ${new Date(quotedRfqs[0].validUntil).toLocaleDateString('en-IN', { day: '2-digit', month: 'short' })}`}
            </p>
          </div>
          <ButtonLink href="/account/rfq" size="sm" className="shrink-0">
            Review
          </ButtonLink>
        </div>
      )}

      {/* Stats ------------------------------------------------------------ */}
      <div className="grid grid-cols-2 gap-3 lg:grid-cols-4">
        <StatCard
          label="Shortlist"
          value={saved.length}
          hint={saved.length > 0 ? 'Ready to compare or quote' : 'Nothing saved yet'}
          icon={Bookmark}
          href="/account/saved"
        />
        <StatCard
          label="Open quotations"
          value={openRfqs.length}
          hint={quotedRfqs.length > 0 ? `${quotedRfqs.length} quoted` : 'None awaiting you'}
          icon={FileText}
          href="/account/rfq"
          tone={quotedRfqs.length > 0 ? 'accent' : 'neutral'}
        />
        <StatCard
          label="Searches"
          value={searches.length}
          hint={`${aiSearches} with the assistant`}
          icon={Search}
          href="/account/searches"
        />
        <StatCard
          label="Conversations"
          value={conversations.length}
          hint="Assistant threads"
          icon={Sparkles}
          href="/account/assistant"
        />
      </div>

      {/* Two-column body -------------------------------------------------- */}
      {/* grid-cols-[minmax(0,1fr)] below lg keeps the stacked columns from
          adopting their widest child's intrinsic width on narrow screens. */}
      <div className="mt-6 grid grid-cols-[minmax(0,1fr)] gap-6 lg:grid-cols-[minmax(0,1.5fr)_minmax(0,1fr)]">
        <div className="min-w-0 space-y-6">
          {/* Recommendations ------------------------------------------- */}
          <SectionCard
            title="Picked up from your last search"
            description={
              latestSearch
                ? `Re-ranked against “${truncateMiddle(latestSearch.query, 62)}”`
                : undefined
            }
            action={
              <Link
                href="/account/searches"
                className="text-[13px] font-medium text-accent-text hover:underline"
              >
                History
              </Link>
            }
            padded={recommended.length === 0}
          >
            {recommended.length === 0 ? (
              <StateBlock
                title="No recommendations yet"
                description="Once you describe a requirement to the assistant, the products that best match it appear here."
                primaryAction={{ label: 'Describe a requirement', href: '/assistant' }}
                compact
              />
            ) : (
              <ul className="divide-y divide-border">
                {recommended.map((result) => (
                  <li key={result.product.id}>
                    <Link
                      href={`/products/${result.product.slug}?q=${encodeURIComponent(latestSearch?.query ?? '')}`}
                      className="flex items-center gap-4 px-5 py-3.5 transition-colors hover:bg-surface-2"
                    >
                      <div className="min-w-0 flex-1">
                        <p className="text-[11px] font-medium tracking-wide text-muted uppercase">
                          {result.product.brand.name}
                        </p>
                        <p className="mt-0.5 truncate text-[14px] font-medium text-text">
                          {result.product.name}
                        </p>
                        <p className="mt-1 truncate font-mono text-[11px] text-faint tnum">
                          {highlightSpecs(result.product, 3)
                            .map((spec) => spec.displayValue)
                            .join(' · ')}
                        </p>
                      </div>

                      <div className="hidden shrink-0 sm:block">
                        <MatchBadge percent={result.explanation.matchPercent} showLabel={false} />
                      </div>

                      <span className="shrink-0 font-mono text-[14px] font-semibold text-text tnum">
                        {formatPrice(result.product.price)}
                      </span>
                    </Link>
                  </li>
                ))}
              </ul>
            )}
          </SectionCard>

          {/* Shortlist -------------------------------------------------- */}
          <SectionCard
            title="Your shortlist"
            description={saved.length > 0 ? pluralize(saved.length, 'product') : undefined}
            action={
              saved.length > 0 && (
                <Link
                  href="/account/saved"
                  className="text-[13px] font-medium text-accent-text hover:underline"
                >
                  View all
                </Link>
              )
            }
          >
            {savedProducts.length === 0 ? (
              <StateBlock
                title="Nothing shortlisted"
                description="Save products while you browse and they collect here, ready to compare or send out as one quotation request."
                primaryAction={{ label: 'Browse products', href: '/products' }}
                compact
              />
            ) : (
              <div className="grid gap-4 sm:grid-cols-2">
                {savedProducts.map((product) => (
                  <ProductCard
                    key={product.id}
                    product={product}
                    highlights={highlightSpecs(product, 2)}
                    dense
                  />
                ))}
              </div>
            )}
          </SectionCard>
        </div>

        {/* Sidebar ------------------------------------------------------- */}
        <div className="min-w-0 space-y-6">
          {/* Activity chart ------------------------------------------- */}
          <SectionCard title="Search activity" description="Last seven days">
            <BarChart data={week} />
            <div className="mt-5 border-t border-border pt-4">
              <p className="mb-2.5 text-[12px] font-medium text-muted">How you searched</p>
              <ShareBar
                segments={[
                  { label: 'Assistant', value: aiSearches, className: 'bg-accent' },
                  {
                    label: 'Keyword',
                    value: searches.length - aiSearches,
                    className: 'bg-surface-3',
                  },
                ]}
              />
            </div>
          </SectionCard>

          {/* Quotations ------------------------------------------------ */}
          <SectionCard
            title="Quotations"
            action={
              rfqs.length > 0 && (
                <Link
                  href="/account/rfq"
                  className="text-[13px] font-medium text-accent-text hover:underline"
                >
                  All
                </Link>
              )
            }
            padded={rfqs.length === 0}
          >
            {rfqs.length === 0 ? (
              <StateBlock
                title="No quotation requests"
                description="Shortlist what you need, then send one request covering all of it."
                primaryAction={{ label: 'Browse products', href: '/products' }}
                compact
              />
            ) : (
              <ul className="divide-y divide-border">
                {rfqs.slice(0, 3).map((rfq) => (
                  <li key={rfq.id}>
                    <Link
                      href={`/account/rfq/${rfq.id}`}
                      className="flex items-center gap-3 px-5 py-3 transition-colors hover:bg-surface-2"
                    >
                      <div className="min-w-0 flex-1">
                        <p className="font-mono text-[12px] text-text tnum">{rfq.reference}</p>
                        <p className="mt-0.5 text-[12px] text-faint">
                          {pluralize(rfq.items.length, 'line')} · {formatRelative(rfq.updatedAt)}
                        </p>
                      </div>
                      <Badge tone={RFQ_TONE[rfq.status]} size="sm">
                        {RFQ_STATUS_LABELS[rfq.status]}
                      </Badge>
                    </Link>
                  </li>
                ))}
              </ul>
            )}
          </SectionCard>

          {/* Notifications --------------------------------------------- */}
          <SectionCard
            title="Notifications"
            description={unread.length > 0 ? `${unread.length} unread` : 'All caught up'}
            action={
              <Link
                href="/account/notifications"
                className="text-[13px] font-medium text-accent-text hover:underline"
              >
                All
              </Link>
            }
            padded={notifications.length === 0}
          >
            {notifications.length === 0 ? (
              <p className="p-5 text-[13px] text-muted">Nothing yet.</p>
            ) : (
              <ul className="divide-y divide-border">
                {notifications.slice(0, 4).map((notification) => (
                  <li key={notification.id} className="px-5 py-3">
                    <div className="flex items-start gap-2.5">
                      {!notification.read && (
                        <span
                          className="mt-1.5 size-1.5 shrink-0 rounded-full bg-accent"
                          aria-label="Unread"
                        />
                      )}
                      <div className={notification.read ? 'ml-4 min-w-0' : 'min-w-0'}>
                        <p className="text-[13px] leading-snug font-medium text-text">
                          {notification.title}
                        </p>
                        <p className="mt-0.5 text-[11px] text-faint">
                          {formatRelative(notification.createdAt)}
                        </p>
                      </div>
                    </div>
                  </li>
                ))}
              </ul>
            )}
          </SectionCard>

          {/* Recently viewed ------------------------------------------- */}
          {recentProducts.length > 0 && (
            <SectionCard
              title="Recently viewed"
              action={
                <Link
                  href="/account/recent"
                  className="text-[13px] font-medium text-accent-text hover:underline"
                >
                  All
                </Link>
              }
              padded={false}
            >
              <ul className="divide-y divide-border">
                {recentProducts.slice(0, 4).map((product) => (
                  <li key={product.id}>
                    <Link
                      href={`/products/${product.slug}`}
                      className="flex items-center gap-3 px-5 py-2.5 transition-colors hover:bg-surface-2"
                    >
                      <Clock className="size-3.5 shrink-0 text-faint" aria-hidden />
                      <span className="min-w-0 flex-1 truncate text-[13px] text-text-2">
                        {product.name}
                      </span>
                      <ArrowRight className="size-3.5 shrink-0 text-faint" aria-hidden />
                    </Link>
                  </li>
                ))}
              </ul>
            </SectionCard>
          )}

          {/* Usage ------------------------------------------------------ */}
          <div className="rounded-xl border border-border bg-surface p-5">
            <div className="flex items-center gap-2">
              <TrendingUp className="size-4 text-accent-text" aria-hidden />
              <h2 className="text-[13px] font-semibold text-text">Plan usage</h2>
            </div>
            <p className="mt-3 font-mono text-2xl font-semibold text-text tnum">
              {searches.length}
              <span className="text-base text-faint"> / 200</span>
            </p>
            <p className="mt-0.5 text-[12px] text-muted">AI searches this month</p>
            <div className="mt-3 h-1.5 overflow-hidden rounded-full bg-border">
              <div
                className="h-full rounded-full bg-accent"
                style={{ width: `${Math.min(100, (searches.length / 200) * 100)}%` }}
                aria-hidden
              />
            </div>
            <p className="mt-3 text-[12px] text-faint">
              Free plan. <Link href="/pricing" className="text-accent-text hover:underline">Compare plans</Link>
            </p>
          </div>
        </div>
      </div>
    </>
  )
}

function greeting(): string {
  const hour = new Date().getHours()
  if (hour < 12) return 'Good morning'
  if (hour < 17) return 'Good afternoon'
  return 'Good evening'
}

function truncateMiddle(text: string, max: number): string {
  if (text.length <= max) return text
  const half = Math.floor((max - 1) / 2)
  return `${text.slice(0, half)}…${text.slice(-half)}`
}
